### ISSUE TITLE
Install all hook types

### ISSUE THREAD

**Issue by EliRibble** [pre-commit/pre-commit#1186] opened 2019-10-23 19:05 UTC
I have a repo with many hooks for different stages in `.pre-commit-config.yaml`. In order for new users who clone my repository to have their hooks installed properly they need to do:

```
pre-commit install
pre-commit install --hook-type commit-msg
pre-commit install --hook-type prepare-commit-msg
```

I'm offering to implement logic to fix this situation, but I want to make sure what I implement is in line with the direction the maintainers want to go in. I could do `pre-commit install --all` and just install a hook for every supported type. That's good enough for me. Alternatively, I could change the logic for `pre-commit install` to read the config file and determine which hooks need to be installed and install those rather than just installing the pre-commit hook.

Are either of these options preferred over the other? Is there a reason not to implement either one?

**Comment by asottile** [comment] 2019-10-23 19:12
this is a dupe of #1139 and #1145 will land in the next release

**Closed** 2019-10-23 19:12 UTC

**Comment by NickLarsenNZ** [comment] 2024-07-19 19:02
@asottile, which PR was this completed in?

**Comment by asottile** [comment] 2024-07-19 19:06
@NickLarsenNZ github shows the linked issues and PRs ^^
