### ISSUE TITLE
Hook Installation Error: ValueError: ZIP does not support timestamps before 1980

### ISSUE THREAD

**Issue by alunduil** [pre-commit/pre-commit#1659] opened 2020-10-24 09:43 UTC
I'm not quite sure if this is the correct place to ask about this or report this but it seems like the best place to start.

When trying to do `pre-commit run --all-files` I get an error when installing black (https://gist.github.com/alunduil/c10c8ea30d5e783b1f9f901edcadd184) rather than the expected successful evaluation of the defined hooks.

I'm trying to work with nix and poetry and the setup can be seen by browsing the files in https://github.com/alunduil/zfs-replicate/pull/118.

Steps that hopefully reproduce the issue:

1. When working on that branch of zfs-replicate
1. Ensure direnv has run: `direnv reload` (requires nix but should not require anything else)
1. Run `pre-commit run --all-files`

Potentially related but I can't tell.  When I'm working in two different Python projects I notice that pre-commit wants to re-use the same environment even though the package sets and Python interpreters might be drastically different.  Is there anyway to have pre-commit cache somewhere that's project specific to avoid different projects causing cache collisions?

Let me know if anything is missing (I'm sure I've overlooked some details).

**Comment by asottile** [comment] 2020-10-24 15:47
this seems to be a problem specific to your computer as I cannot reproduce and your travis build cannot reproduce

do you happen to have this return anything? `env | grep SOURCE_DATE_EPOCH`

is your filesystem configured to set really old dates by default?  is your computer in pre-1980 clock time?

you can probably isolate your problem by doing the following:

```bash
git clone https://github.com/psf/black
cd black
git checkout 19.10b0
virtualenv venv
venv/bin/pip install .
```

as for this question:

>  Is there anyway to have pre-commit cache somewhere that's project specific to avoid different projects causing cache collisions?

pre-commit doesn't install from anything other than the `.pre-commit-config.yaml` so there isn't really anything """project specific""".  if you could elaborate on what you think is a collision I'd be happy to explain a specific scenario

**Comment by alunduil** [comment] 2020-10-25 09:23
Thanks for the response and assistance @asottile .  I do expect it's something about my environment and not necessarily a problem with pre-commit but as pre-commit is the only thing acting this way that I've observed (everything else runs smoothly including pip installs) I had to start asking here to try and figure things out.

Requested answers:

 `env | grep SOURCE_DATE_EPOCH`
```
SOURCE_DATE_EPOCH=1
```

I don't believe my filesystem is configured to set really old dates by default.   Doing a quick `touch foo` results in a timestamp of the current locale as expected.

I don't believe my computer is in a pre-1980 clock time but I guess I'm not sure how to verify either.  It reports the same time as other devices with network time sync correctly.

Cloning black and setting up a minimal nix-shell environment with envrc does indeed reproduce this so I'll have to investigate further.  I did gather the above information in an identical environment setup for zfs-replicate.

For the last question I had, I noticed that pre-commit uses a central cache location in ~/.cache/pre-commit and it seems this gets re-used even if I switch to another Python project (different virtualenv, different interpreter, etc).  If this isn't the case, then might I ask what's being cached in this location?

Thanks again for the pointers.  I'll see if I can find an answer on black by following up there now that I know how to reproduce in their development flow.

**Comment by alunduil** [comment] 2020-10-25 09:46
If anyone else needs to stumble onto this.  I found that changing the environment to use python3.6 instead of the latest allows black to pip install correctly.  I'll be verifying this against the other projects but it looks like this is a black issue and not a pre-commit issue.  Thanks for the assistance again.

**Comment by alunduil** [comment] 2020-10-25 09:53
Hmm, now when using that environment, I get instead: https://gist.github.com/alunduil/790b9df8c312a18862022859a2280bf4

What is a healthy environment?  The assertion provide no guidance on how to resolve this issue.  Let me know what more details about my environment would be useful.

**Comment by asottile** [comment] 2020-10-25 16:48
do you know why you have `SOURCE_DATE_EPOCH=1`? that's what's breaking the zip module

unset that!

**Comment by asottile** [comment] 2020-10-25 16:50
> For the last question I had, I noticed that pre-commit uses a central cache location in ~/.cache/pre-commit and it seems this gets re-used even if I switch to another Python project (different virtualenv, different interpreter, etc). If this isn't the case, then might I ask what's being cached in this location?

yes that's where the environments are stored -- please like I asked list an actual issue you're having with this

**Comment by asottile** [comment] 2020-10-25 16:51
> Cloning black and setting up a minimal nix-shell environment with envrc does indeed reproduce this

given this isn't a problem with pre-commit then => closing

**Closed by asottile** 2020-10-25 16:51 UTC
Labels: question

**Comment by alunduil** [comment] 2020-10-27 18:44
> do you know why you have `SOURCE_DATE_EPOCH=1`? that's what's breaking the zip module
> 
> unset that!

I'm not sure but I'll start investigating that and see what I can find.  Thanks for the pointers again.
