### ISSUE TITLE
Handle wrongly indented .pre-commit-config.yaml

### ISSUE THREAD

**Issue by mitzkia** [pre-commit/pre-commit#979] opened 2019-03-25 13:51 UTC
Of course it was my fault, but it takes some time util I found the problem. 
The question is could pre-commit display a message (warning) about the wrongly indented 
.pre-commit-config.yaml? 

* .pre-commit-config.yaml with wrong indentation:
```
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
    args: [--some-args]
```

* pre-commit will run with no errors (flake8 was executed without any additional args)

* the value of `data` variable in bad case from: https://github.com/pre-commit/pre-commit/blob/da00fa98f9e274e2d3ef8f756566f1946dc79e36/pre_commit/clientlib.py#L258
```
[
    OrderedDict(
        [
            ('repo', 'https://gitlab.com/pycqa/flake8'), 
            ('rev', '3.7.7'), 
            ('hooks', [OrderedDict([('id', 'flake8')])]), 
            ('args', ['--some-args'])
        ]
    )
]
```

* The value of the `data` variable in the valid/good case is:
```
[
    OrderedDict(
        [
            ('repo', 'https://gitlab.com/pycqa/flake8'), 
            ('rev', '3.7.7'), 
            ('hooks', [OrderedDict([('id', 'flake8'), ('args', ['--some-args'])])])
        ]
    )
]
```

* In my opinion this case can be handled with a check of keys in the OrderedDict, there can not be other keys (at the top level) only: 'repo', 'rev' and 'hooks'.

**Comment by asottile** [comment] 2019-03-25 13:58
This is a duplicate of #965

**Closed by asottile** 2019-03-25 13:58 UTC

**Comment by mitzkia** [comment] 2019-03-25 14:00
Thanks, sorry, did not find the duplicated issue. 
Maybe I will try to fix this :)
