### ISSUE TITLE
"OSError: [Errno 17] File exists" upon trying to commit

### ISSUE THREAD

**Issue by galstest** [pre-commit/pre-commit#184] opened 2015-01-09 01:45 UTC
See here for the log file tail: https://pb.yelpcorp.com/113047

I had some issues with the pre-commit hooks while trying to merge a conflict file.
The error showed something regarding some repo under ~/.pre-commit
Looking for a solution I end up removing that repo dir. Sorry but I can't find where I got this solution from (it has been a few days ago).
From that point on I kept getting this: https://pb.yelpcorp.com/113052 output when trying to commit.
The log file is the one I've pasted above.

Consulting with buck from the webcore group he suggested changing the name of .pre-commit dir which solved it (all hooks were re-installed).

I've sent you a tar of the .pre-commit dir that had that problem.

**Comment by asottile** [comment] 2015-01-09 15:55
@galstest github is public, don't post links to our internal things!

**Comment by asottile** [comment] 2015-01-09 16:01
I can reproduce your exception by doing the following:

1. `pre-commit run --all-files`
2. `rm ~/.pre-commit/repo*`
3. `pre-commit run --all-files`

However, I'm going to close this as wontfix since it is not a supported workflow.  The only time pre-commit will delete things is during `pre-commit clean` when it'll delete `~/.pre-commit` outright.  Whoever told you to reach inside the `.pre-commit` directory and delete things was misleading you.  If there's any documentation that indicates that, please bring it to my attention :)

I wish you had the trace from the original error that you "fixed" by deleting the repo -- that probably would have been actionable...

**Closed by asottile** 2015-01-09 16:01 UTC

**Comment by galstest** [comment] 2015-01-09 18:59
@asottile mmm I thought pb links require credentials. thanks for commenting on that.

**Comment by asottile** [comment] 2015-01-09 19:03
@galstest right, but this is an open source project and if only people in yelp engineering can read your stacktrace that isn't great :/
