### ISSUE TITLE
Diff-only linting

### ISSUE THREAD

**Issue by Holzhaus** [pre-commit/pre-commit#1310] opened 2020-02-03 21:22 UTC
It would be really nice to have diff-only linting for large legacy codebases.

Would there an interest in adding another hook option that lets you specify a regex that parses the linter output and checks if the line are part of diff?

Here's an example for `flake8`:
```yaml
diff_regex: '^(?P<file>[^:]*):(?P<line>):.*$'
diff_only: true
```
If the line `line` in the file `file` was changed, show the output, if not then don't (and ignore the return code).

Related issue: #380

**Comment by asottile** [comment] 2020-02-03 21:24
duplicate of #380

**Closed by asottile** 2020-02-03 21:24 UTC
