### ISSUE TITLE
Pre-push hook runs on all files from merge commit

### ISSUE THREAD

**Issue by JKillian** [pre-commit/pre-commit#952] opened 2019-02-21 18:42 UTC
Say I have a pre-commit config with only pre-push hooks and the following git setup:

```
A <-- B (master)
 \  
  C (feature)
```

When I run `git push -u origin feature` to push `feature` initially, the files changed in C are checked correctly. (The `pre-push` hook computes options something like `--origin C --source A`.)

Now lets say I merge `master` in to `feature` and make another commit.

```
A <-- B (master)
 \      \
  C <--- D (feature)
```

Now, the pre-push hook causes all the changes in B to get checked, even if they weren't conflicting, which can include a large amount of irrelevant changes. The `pre-push` hook computes options for running pre-commit as `--origin D --source A`.

```
A <-- B (master)
 \      \
  C <--- D <--- E (feature)
```

If I make another commit, pre-commit is run with `--origin E --source A` which still checks all the changes from commit B which is irrelevant to my branch.

Is there anyway to configure/work with pre-commit to avoid this behavior? Thanks!

**Comment by asottile** [comment] 2019-02-21 18:44
I believe this is a duplicate of #860 -- waiting for a patch which can better figure out the correct set of files to run on :)

**Comment by asottile** [comment] 2019-02-21 18:50
I just reread #860 and adjusted the title -- let's continue the discussion there :tada:

**Closed by asottile** 2019-02-21 18:50 UTC

**Comment by JKillian** [comment] 2019-02-21 18:52
Agreed this is a duplicate, thanks for the quick response! Sorry I didn't see that other issue previously

**Comment by asottile** [comment] 2019-02-21 18:53
No problem! I improved the title so it is more discoverable in the future
