### ISSUE TITLE
Docs request: Add pipx as an installation option

### ISSUE THREAD

**Issue by itsayellow** [pre-commit/pre-commit#1719] opened 2020-11-28 05:54 UTC
I'm one of the lead maintainers of pipx, and I definitely love to use pre-commit while developing pipx.

I was wondering if pre-commit would be interested in listing pipx as an installation method?  If so, I would be happy to contribute a PR for the docs.

**Comment by asottile** [comment] 2020-11-28 06:05
duplicate of https://github.com/pre-commit/pre-commit.com/pull/421

**Closed by asottile** 2020-11-28 06:05 UTC
