### ISSUE TITLE
Support extending and/or subtracting hooks from other YAML file

### ISSUE THREAD

**Issue by TheButlah** [pre-commit/pre-commit#1392] opened 2020-04-14 15:47 UTC
It would be amazing if we could include pre-commit yaml files in other files, and even better if we could add or subtract hooks from the extended file. This would mean we could ensure that for example, the hooks enforced in CI is a superset of a more minimal setup which would be the default hooks, and someone can base their local customized hooks on on either the minimal file or the full CI file and customize them easily.

**Comment by TheButlah** [comment] 2020-04-14 15:49
Related to #731 , but this is a bit more advanced of a use case, and also the solution in #731 feels like a hack

**Comment by asottile** [comment] 2020-04-14 15:57
This is a duplicate of a bunch of issues -- I won't be implementing inclusion for technical reasons, you can read the duplicates here:
- #466 
- #731
- #1069
- #1158
- #1203 
- #1308

thanks for the issue nonetheless!

**Comment by TheButlah** [comment] 2020-04-14 15:57
Motivation for proposal:

My org is a small group (~15) and we are having a lot of trouble getting people to use this tool. There are roughly 3 camps of people: 
1. Some are ideologically opposed to the notion of tools modifying their code or interfering with committing even if the commit is broken, and want to just look at CI and fix what went wrong after the fact. They might or might not be ok with a smaller set of hooks that don't modify any files, but protect against the worst offenders - things like committing merge conflicts, and committing large files.
2. Some want the ability to be able to run all the CI checks locally on every commit - this would be the conventional use case of pre-commit, where there is a yml file committed with the repo and that is what the server CI runs, as well as what developers `pre-commit install`.
3. Some want more customization - they want to run some subset of the CI hooks, and maybe even add on a few.

To address these 3 camps of people, we wanted to make a distinction between the minimal set of pre-commit hooks and the CI hooks. We would have the toplevel `.pre-commit-config.yml` be the minimal possible set of hooks - mostly things to prevent polluting git history and making rebases extremely hard. There would also be a file for the server hooks, which _would be a superset of the hooks in the minimal file_. This would hopefully encourage group 1 to use pre-commit and help people out, while allowing group 2 to use the full CI hooks by installing the CI file rather than the minimal one.

However, I have some concerns with this approach. There doesn't seem to be a way for pre-commit to install hooks from two different files at the same time. This means that we need to duplicate the minimal set of hooks in the CI file. Additionally, if someone wants a middle ground between the minimal file and the full file, or add new hooks, they must write their own file. Managing these files is brittle and redundant, as if we want to add new hooks to the minimal file we must also update the server file, and if we change either, every custom version likely ought to  change too.

**Closed by asottile** 2020-04-14 15:57 UTC

**Comment by asottile** [comment] 2020-04-14 15:59
fwiw, in one repository I manage (private) we're using the multiple-file approach with success.  we use a test to ensure that the relationships of the contents are managed properly

**Comment by TheButlah** [comment] 2020-04-14 16:00
Is this a technical or ideological opposition to supporting extending and removing hooks from other files? If its a technical one, would you accept a PR for it?

**Comment by asottile** [comment] 2020-04-14 16:02
it is both technical and ideological and will not be accepted, no.

**Comment by TheButlah** [comment] 2020-04-14 16:07
Can you provide guidance on how to ensure that the file relationships are managed properly? That is between the minimal hooks and the full set of hooks.

**Comment by marcjay** [comment] 2020-04-14 16:10
15 is a fairly small org and I wonder if the solution here is an organisational one rather than any technical changes to a tool like pre-commit? Ultimately you can never satisfy every person in a team - do you not need to come to a majority decision and just follow it as a team? Personally I wouldn’t be indulging the people in camp 1 - it’s not a particularly sensible or efficient stance

**Comment by asottile** [comment] 2020-04-14 16:10
our script basically just loads the yaml and makes sure one contains all the stuff from the other (and produces an error when they are not the same) -- probably could even be (meta) used as a pre-commit hook

**Comment by TheButlah** [comment] 2020-04-14 16:32
OK, so it sounds like a diff is sufficient. I'll go that approach for now - its easier than an organizational one :P
