### ISSUE TITLE
Auto-Install different hook types

### ISSUE THREAD

**Issue by particledecay** [pre-commit/pre-commit#1338] opened 2020-02-20 16:57 UTC
The `pre-commit install` command should (maybe via use of an `--auto` flag?) detect all of the defined hook types in the `.pre-commit-config.yaml` file and install those automatically.

Currently, if I have one pre-commit hook and another commit-msg hook, this is how I'd have to install:

```bash
pre-commit install -t pre-commit -t commit-msg
```

The information for what types of hooks are available to install is already located in the `.pre-commit-config.yaml`. Having to specify this again during the install process introduces the possibility for human error. I believe a sane default would be to auto-detect hook types and install all the applicable types. However, if you don't want to break backward compatibility, I would suggest adding a flag to trigger this behavior (such as `--auto` or `--auto-hook-types` or `--detect` or something).

**Comment by asottile** [comment] 2020-02-20 17:01
duplicate of #1186 and #1139 -- I'd suggest reading the extended discussion there 👍

**Closed by asottile** 2020-02-20 17:01 UTC

**Comment by asottile** [comment] 2020-02-20 17:04
huh maybe that one is missing it but I'm having trouble finding the exact duplicate -- anyway installing all hook types is problematic because of a couple reasons:

1. not all hook types are supported for all git versions
2. the default `stages` for hooks is *every hook type* (and this is not changing) -- so every hook would be installed always
3. new hook types are added occasionally and you'd mysteriously be opted into them
4. I prefer the explicit nature of the command as it is today

**Comment by gschwaer** [comment] 2021-12-15 13:57
Hi @asottile, I would agree with @particledecay on
> a sane default would be to auto-detect hook types and install all the applicable types. 

If only the hooks from the config are installed and not all, I guess that is already good for reason 1 and 3.

On reason 2: Using the hook types in `stages` allows the hook developer to specify at which stage their code need to be executed. But there is no way to specify which git hooks need to be installed for this pre-commit hook to work at all. This information is actually quite implicit in the notion of `stages`. It is just not used on installation.

Depending on the project specific configuration of the pre-commit repos some monsters can come up, like:
```bash
pre-commit -t post-checkout -t pre-commit -t push -t commit-msg -t post-commit
```
In the end the user will probably either be asked to copy paste this line into a terminal or it will be hidden in a setup script/Makefile/... I don't think either would be in favor of reason 4.

I think there might be a user friendly way to solve this, with an interactive prompt, for example:
```bash
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
The pre-commit hook 'commitizen' requires commit-msg. Install this hook? [Y/n] Y
pre-commit installed at .git/hooks/commit-msg
```
So when cloning a repo and finding a `.pre-commit-config.yaml` I then don't have to go through the documentation to search with which arguments I have to call `pre-commit install` for the config to work. I think that would take away much pre-commit related load on the user at install time and on the developer when documenting.

What do you think?

**Comment by asottile** [comment] 2021-12-15 17:10
please read the comment directly above the one you posted for my answer to this and in the future do not bump year old closed threads
