### ISSUE TITLE
Documentation Bug: The Regular Expression section uses redundant anchors in the example

### ISSUE THREAD

**Issue by adrian-kiwibank** [pre-commit/pre-commit#2611] opened 2022-11-24 22:13 UTC
### search you tried in the issue tracker

regex anchor

### describe your issue

I was referring to the example in the Regular Expressions section of the documentation at [pre-commit.com/](https://pre-commit.com/).
This showed an example exclude with anchors (`^...$`):
```
    -   id: my-hook
        exclude: |
            (?x)^(
                path/to/file1.py|
                path/to/file2.py|
                path/to/file3.py
            )$
```
This would imply that a regular expression without anchors could be used to perform a match against a partial path, for example, to ignore everything in a `.git` directory by using simply `/.git/` but it turns out the anchors are implicitly added by pre-commit so that specifying a `.git` directory needs leading and trailing `.*`:  '.*/.git/.*`

I suggest that the example should not show the anchors and should say that they are implicitly added.

### pre-commit --version

pre-commit v2.20.0

### .pre-commit-config.yaml

```yaml
-   id: my-hook
        exclude: |
            (?x)^(
                path/to/file1.py|
                path/to/file2.py|
                path/to/file3.py
            )$
```

**Comment by asottile** [comment] 2022-11-24 22:59
you're not correct, please show an actual example so I can directly address your misunderstanding

note that excluding `.git` is also nonsense because pre-commit only passes files which are checked in

**Closed** 2022-11-27 21:02 UTC

**Comment by adrian-kiwibank** [comment] 2022-11-27 21:22
> you're not correct, please show an actual example so I can directly address your misunderstanding
> 
> note that excluding `.git` is also nonsense because pre-commit only passes files which are checked in

@asottile : My git workspace has a sub-directory called `overrides`. 
I configured `exclude: /overrides/` expecting that it would match every path in the sub-directory.
But files in that subdirectory were still processed.
When I changed the configuration to `exclude: .*/overrides/.*` then the files in that subdirectory were not processed.

From this I inferred that the `exclude` regular expression implicitly anchors the check with `^ ... $`

**Comment by asottile** [comment] 2022-11-27 21:32
that's not possible -- try crafting a reproducible example

**Comment by asottile** [comment] 2022-11-27 21:34
for example, here's a small reproducible example which refutes your assertion:

```yaml
$ cat .pre-commit-config.yaml 
# exclude: /overrides/
repos:
-   repo: meta
    hooks:
    -   id: identity
$ git ls-files
.pre-commit-config.yaml
foo/overrides/a/b
$ pre-commit run --all-files
identity.................................................................Passed
- hook id: identity
- duration: 0.02s

.pre-commit-config.yaml
foo/overrides/a/b

$ sed -i 's/# //g' .pre-commit-config.yaml 
$ pre-commit run --all-files
identity.................................................................Passed
- hook id: identity
- duration: 0.02s

.pre-commit-config.yaml

```
