### ISSUE TITLE
Failing to correctly restore changes after stashed during commit

### ISSUE THREAD

**Issue by sbland** [pre-commit/pre-commit#1760] opened 2021-01-15 14:08 UTC
After committing some changes when other changes were not staged the unstaged changes were stashed but then seemed to fail to restore. This resulted in the changes appearing to be reverted. I managed to restore these changes from the pre-commit cache using `git apply "/c/Users/xxxx/.cache/pre-commit/patch16107164`
I think this was caused by an unstaged file being open in Excel so permissions were denied to delete the file to stash it.

Pre-commit vesion: `2.7.1`

Plugins using: 
- Trim Trailing Whitespace
- Fix End of Files
- Check Yaml
- Check for case conflicts
- Check JSON
- autopep8
- type annotations not comments
- flake8

See below for the git logs from Vscode
```
> git add -A -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
warning: LF will be replaced by CRLF in .../Defaults/snapshots/snap_config_init_processes_test.py.
The file will have its original line endings in your working directory
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse match-xxxxx-ui-xxxxx
> git rev-parse --symbolic-full-name match-xxxxx-ui-xxxxx@{u}
> git rev-list --left-right match-xxxxx-ui-xxxxx...refs/remotes/origin/match-xxxxx-ui-xxxxx
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git show --textconv :.../Defaults/snapshots/snap_config_init_processes_test.py
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse match-xxxxx-ui-xxxxx
> git rev-parse --symbolic-full-name match-xxxxx-ui-xxxxx@{u}
> git rev-list --left-right match-xxxxx-ui-xxxxx...refs/remotes/origin/match-xxxxx-ui-xxxxx
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git show --textconv :.../Defaults/snapshots/snap_config_init_processes_test.py
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\xxxxxx\.cache\pre-commit\patch1610716472.
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\xxxxxx\\AppData\\Local\\Programs\\Git\\mingw64\\libexec\\git-core\\git.EXE', 'checkout', '--', '.')
return code: 255
expected return code: 0
stdout: (none)
stderr:
    error: unable to unlink old 'examples/xxxx_xxxxx/output/...-xxxxx-ui-copy/xxxx_output.csv': Invalid argument
    
Check the log at C:\Users\xxxxxx\.cache\pre-commit\pre-commit.log
> git config --get-all user.name
> git config --get-all user.email
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git show --textconv :.../Defaults/snapshots/snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git show --textconv :.../Defaults/snapshots/snap_config_init_processes_test.py
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse match-xxxxx-ui-xxxxx
> git rev-parse --symbolic-full-name match-xxxxx-ui-xxxxx@{u}
> git rev-list --left-right match-xxxxx-ui-xxxxx...refs/remotes/origin/match-xxxxx-ui-xxxxx
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
> git ls-files --stage -- C:\Users\xxxxxx\source\...\...\Defaults\snapshots\snap_config_init_processes_test.py
> git cat-file -s 7904983829e8091ba4d9b8f56b690f5fe8163805
> git show --textconv :.../Defaults/snapshots/snap_config_init_processes_test.py
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to C:\Users\xxxxxx\.cache\pre-commit\patch1610716507.
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
autopep8.................................................................Passed
type annotations not comments............................................Passed
flake8...................................................................Passed
[INFO] Restored changes from C:\Users\xxxxxx\.cache\pre-commit\patch1610716507.
```

pre-commit.log
```
$ cat pre-commit.log
### version information


pre-commit version: 2.7.1
sys.version:
    3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
sys.executable: c:\users\xxxxx\source\xxxxx\venv\scripts\python.exe
os.name: nt
sys.platform: win32


### error information


An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Git\\mingw64\\libexec\\git-core\\git.EXE', 'checkout', '--', '.')
return code: 255
expected return code: 0
stdout: (none)
stderr:
    error: unable to unlink old 'examples/xxxxxx_multiplicative/output/xxxxx-xxx-ui-copy/xxxxx_output.csv': Invalid argument




Traceback (most recent call last):
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\error_handler.py", line 63, in error_handler
    yield
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\main.py", line 362, in main
    return hook_impl(
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\commands\hook_impl.py", line 217, in hook_impl
    return retv | run(config, store, ns)
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\commands\run.py", line 372, in run
    exit_stack.enter_context(staged_files_only(store.directory))
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\staged_files_only.py", line 92, in staged_files_only
    with _intent_to_add_cleared(), _unstaged_changes_cleared(patch_dir):
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\staged_files_only.py", line 61, in _unstaged_changes_cleared
    cmd_output_b('git', 'checkout', '--', '.', env=no_checkout_env)
  File "c:\users\xxxxx\source\xxxxx\venv\lib\site-packages\pre_commit\util.py", line 157, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Git\\mingw64\\libexec\\git-core\\git.EXE', 'checkout', '--', '.')
return code: 255
expected return code: 0
stdout: (none)
stderr:
    error: unable to unlink old 'examples/xxxxxx_multiplicative/output/xxxxx-xxx-ui-copy/xxxxx_output.csv': Invalid argument

```

**Comment by asottile** [comment] 2021-01-15 16:41
dupe of #1540

**Closed by asottile** 2021-01-15 16:41 UTC
