### ISSUE TITLE
.pre-commit-config.yaml does not exist when you use yml instead of yaml

### ISSUE THREAD

**Issue by eduzen** [pre-commit/pre-commit#1451] opened 2020-05-11 23:30 UTC
```
$ pre-commit run --all-files
An error has occurred: InvalidConfigError:
=====> .pre-commit-config.yaml does not exist
Check the log at /Users/eduardo.enriquez/.cache/pre-commit/pre-commit.log

$ ls .pre-commit.config*
.pre-commit-config.yml
```

AFAIK yml or yaml are both valid. A lot of other tools allows to use both of them. I don't know if it's a fair point, but I think it is also not hard to implement.

**Comment by asottile** [comment] 2020-05-11 23:31
duplicate of #702

a lot of other tools allow both, but pre-commit does not

**Comment by asottile** [comment] 2020-05-11 23:32
fwiw, [the official spelling is yaml](https://yaml.org/faq.html)

**Closed by asottile** 2020-05-11 23:31 UTC

**Comment by marcjay** [comment] 2020-05-11 23:45
Is the comment from #702 of:

> if you can make a tested PR for this behaviour I'd be happy to take it.

Still true? I’ve been using pre-commit for over a year and still bumped up against this just last week. 30 seconds of “but there is a config file! Ahhh I see the problem”. Understand the hesitation, but I’m a fan of the “be conservative in what you do, be liberal in what you accept from others” [principle](https://en.wikipedia.org/wiki/Robustness_principle)

**Comment by asottile** [comment] 2020-05-11 23:54
I'd rather not, especially given the official stance on `.yaml`

**Comment by marcjay** [comment] 2020-05-12 00:11
It doesn’t really feel like pre-commit’s job to police that though. Their stance is a preference not a point about compatibility, so it seems odd to me that a preference is being imposed forcefully, when other YAML driven tools like Ansible or K8s don’t concern themselves with it. Just seems a bit user-unfriendly/hostile I guess

**Comment by asottile** [comment] 2020-05-12 00:14
there's no force here, if you want to use `.yml` (or any other location / name you want) you can use `--config`.

my preference is `.yaml` and to not have multiple ways to do things and so that's the way it's going to be.  adding complexity, maintenance burden, documentation confusion, etc. because someone else's preference is `.yml` is not something I'd like to deal with.
