### ISSUE TITLE
pre-commit clean does not work under Windows

### ISSUE THREAD

**Issue by Helveg** [pre-commit/pre-commit#1284] opened 2020-01-15 01:05 UTC
Yields the following error:

```
An unexpected error has occurred: OSError: [WinError 145] The directory is not empty: 'C:\\Users\\robin/.cache\\pre-commit'
Check the log at C:\Users\robin/.cache\pre-commit\pre-commit.log
```

**Comment by asottile** [comment] 2020-01-15 01:06
please attach the full log, this report is useless without it -- thanks!

**Comment by asottile** [comment] 2020-01-15 01:07
for what it's worth, it works for me:

```
C:\Users\Anthony\workspace\pre-commit>venv\Scripts\pre-commit.exe clean
Cleaned C:\Users\Anthony/.cache\pre-commit.
```

**Comment by Helveg** [comment] 2020-01-15 01:10
It turned out to be an issue with having a subfolder open in Explorer, it's just an inaccurate error message.

### version information

```
pre-commit version: 1.21.0
sys.version:
    3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
sys.executable: c:\users\robin\anaconda3\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: OSError: [WinError 145] The directory is not empty: 'C:\\Users\\robin/.cache\\pre-commit'
```

```
Traceback (most recent call last):
  File "c:\users\robin\anaconda3\lib\site-packages\pre_commit\error_handler.py", line 72, in error_handler
    yield
  File "c:\users\robin\anaconda3\lib\site-packages\pre_commit\main.py", line 324, in main
    return clean(store)
  File "c:\users\robin\anaconda3\lib\site-packages\pre_commit\commands\clean.py", line 14, in clean
    rmtree(directory)
  File "c:\users\robin\anaconda3\lib\site-packages\pre_commit\util.py", line 232, in rmtree
    shutil.rmtree(path, ignore_errors=False, onerror=handle_remove_readonly)
  File "c:\users\robin\anaconda3\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\robin\anaconda3\lib\shutil.py", line 401, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\robin\anaconda3\lib\shutil.py", line 399, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\robin/.cache\\pre-commit'

```

**Comment by asottile** [comment] 2020-01-15 01:12
can you show the contents of that directory? are you also perhaps running pre-commit in multiple tabs?  does it succeed when rerun?

**Comment by asottile** [comment] 2020-01-15 01:12
ah ok that makes sense

yeah you can't delete things on windows when they're in use -- closing as not a bug

**Closed by asottile** 2020-01-15 01:12 UTC
Labels: question, windows
