### ISSUE TITLE
Stashed changes conflicted with hook auto-fixes... Rolling back fixes...

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [pre-commit/pre-commit#1787] opened 2021-02-06 13:33 UTC
Using
 
```
▶ pre-commit --version
pre-commit 2.10.0
```

on MacOS Catalina.

I have a directory full of (not only, but mostly) `terraform` files as also terragrunt hcl config.

Using this `pre-commit` config

```
▶ cat .pre-commit-config.yaml
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
      - id: terraform_tfsec
      - id: terragrunt_fmt
```

The following error comes up when running pre-commit

```
[WARNING] Stashed changes conflicted with hook auto-fixes... Rolling back fixes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/pantelis/.cache/pre-commit/patch1612618048')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: unrecognized input

Check the log at /Users/pantelis/.cache/pre-commit/pre-commit.log
```

and the log

```
### version information

pre-commit version: 2.10.0
sys.version:
    3.9.0 (default, Dec  6 2020, 18:02:34)
    [Clang 12.0.0 (clang-1200.0.32.27)]
sys.executable: /usr/local/opt/python@3.9/bin/python3.9
os.name: posix
sys.platform: darwin

### error information

An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/pantelis/.cache/pre-commit/patch1612618267')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: unrecognized input


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 20, in _git_apply
    cmd_output_b('git', *args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'apply', '--whitespace=nowarn', '/Users/pantelis/.cache/pre-commit/patch1612618267')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: unrecognized input


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 68, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 23, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/pantelis/.cache/pre-commit/patch1612618267')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: unrecognized input


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 20, in _git_apply
    cmd_output_b('git', *args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'apply', '--whitespace=nowarn', '/Users/pantelis/.cache/pre-commit/patch1612618267')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: unrecognized input


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.9/site-packages/pre_commit/main.py", line 378, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/commands/run.py", line 405, in run
    return _run_hooks(config, hooks, args, environ)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 513, in __exit__
    raise exc_details[1]
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 498, in __exit__
    if cb(*exc_details):
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 93, in staged_files_only
    yield
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 78, in _unstaged_changes_cleared
    _git_apply(patch_filename)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/staged_files_only.py", line 23, in _git_apply
    cmd_output_b('git', '-c', 'core.autocrlf=false', *args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'core.autocrlf=false', 'apply', '--whitespace=nowarn', '/Users/pantelis/.cache/pre-commit/patch1612618267')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    error: unrecognized input
```

**Comment by asottile** [comment] 2021-02-06 17:17
can you show the contents of the patch file it mentions?

can you also share your `.gitattributes` -- this may be another case of #776 which I believe is a bug in `git` itself and I haven't gotten any traction on the mailing list

**Comment by pantelis-karamolegkos** [comment] 2021-02-06 18:35
Actually I am using `git-crypt` so the `patch` file contains sensitive info.

**Comment by asottile** [comment] 2021-02-06 18:38
this is a dupe of #776 then

**Closed by asottile** 2021-02-06 18:38 UTC
Labels: bug

**Comment by yuklia** [comment] 2021-03-23 10:38
hi, @pantelis-karamolegkos !
how did you manage to solve this issue?

thanks in advance!
