### ISSUE TITLE
CalledProcessError on install

### ISSUE THREAD

**Issue by yhoiseth** [pre-commit/pre-commit#1386] opened 2020-04-06 12:28 UTC
Throughout the day, I've been getting intermittent errors in CI and locally when running `pre-commit`. Output from `pre-commit.log`:

### version information

```
pre-commit version: 2.1.1
sys.version:
    3.7.7 (default, Mar 10 2020, 15:43:33)
    [Clang 11.0.0 (clang-1100.0.33.17)]
sys.executable: /Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/bin/python3.7
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/bin/python3.7', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/yngve/.cache/pre-commit/repo4tbfp50l/node_env-default')
return code: 1
expected return code: 0
stdout: (none)
stderr:
     * Install prebuilt node (13.12.0) .
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 1517, in <module>
        main()
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 1113, in main
        create_environment(env_dir, opt)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 936, in create_environment
        install_node(env_dir, src_dir, opt)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 700, in install_node
        install_node_wrapped(env_dir, src_dir, opt)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 723, in install_node_wrapped
        download_node_src(node_url, src_dir, opt, prefix)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 552, in download_node_src
        dl_contents = io.BytesIO(urlopen(node_url).read())
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 470, in read
        s = self._safe_read(self.length)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 622, in _safe_read
        raise IncompleteRead(b''.join(s), amt)
    http.client.IncompleteRead: IncompleteRead(14843657 bytes read, 16504772 more expected)

```

```
Traceback (most recent call last):
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/error_handler.py", line 54, in error_handler
    yield
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/main.py", line 351, in main
    args=args.rest[1:],
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/commands/hook_impl.py", line 180, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/commands/run.py", line 337, in run
    install_hook_envs(hooks, store)
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/repository.py", line 200, in install_hook_envs
    _hook_install(hook)
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/repository.py", line 83, in _hook_install
    hook.prefix, hook.language_version, hook.additional_dependencies,
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/languages/node.py", line 75, in install_environment
    cmd_output_b(*cmd)
  File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/pre_commit/util.py", line 140, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/bin/python3.7', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/yngve/.cache/pre-commit/repo4tbfp50l/node_env-default')
return code: 1
expected return code: 0
stdout: (none)
stderr:
     * Install prebuilt node (13.12.0) .
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 1517, in <module>
        main()
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 1113, in main
        create_environment(env_dir, opt)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 936, in create_environment
        install_node(env_dir, src_dir, opt)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 700, in install_node
        install_node_wrapped(env_dir, src_dir, opt)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 723, in install_node_wrapped
        download_node_src(node_url, src_dir, opt, prefix)
      File "/Users/yngve/.local/share/virtualenvs/entrepedia-lgvwzfOB/lib/python3.7/site-packages/nodeenv.py", line 552, in download_node_src
        dl_contents = io.BytesIO(urlopen(node_url).read())
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 470, in read
        s = self._safe_read(self.length)
      File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 622, in _safe_read
        raise IncompleteRead(b''.join(s), amt)
    http.client.IncompleteRead: IncompleteRead(14843657 bytes read, 16504772 more expected)
```

### Additional information

The relevant section of `.pre-commit-config.yaml` is:

```yaml
repos:
  …
  - repo: https://github.com/prettier/prettier
    rev: 2.0.2
    hooks:
      - id: prettier

```

The error occurs after 

```
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

in the console output.

I have also been getting some 500 errors.

I assume this is a problem with a server somewhere, but it's not clear which server. My first hunch is GitHub, considering that I'm referencing a GitHub repo, but https://www.githubstatus.com/ has been green all day.

**Comment by asottile** [comment] 2020-04-06 16:57
Duplicate of #1385

**Closed by asottile** 2020-04-06 16:57 UTC
