### ISSUE TITLE
How to run pre-commit inside folder

### ISSUE THREAD

**Issue by imomaliev** [pre-commit/pre-commit#1110] opened 2019-08-06 08:18 UTC
Hi! I have project structure like this
```
.
├── README.md
├── backend
│   ├── Pipfile
│   ├── Pipfile.lock
│   ├── mypy.ini
│   ├── pylintrc
│   ├── pyproject.toml
│   ├── src
│   ├── tests
│   └── tox.ini
├── docker
│   ├── backend
│   └── postgres
├── docker-compose.yml
└── .pre-commit-config.yaml

```

I would like to run pre-commit's flake8 inside `backend` folder, how could I achieve this?

**Comment by naktu** [comment] 2019-08-06 08:21
Hi! Send you path via args.

**Comment by imomaliev** [comment] 2019-08-06 08:30
@naktu it wouldn't work correctly. I need it to be run from inside folder not to have run on folder. 

it should be like this
```
cd backend/

**Comment by naktu** [comment] 2019-08-06 08:37
Can you show your pre-commit configuration file?

**Comment by imomaliev** [comment] 2019-08-06 08:39
@naktu 
```
default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        name: black
        language: system
        entry: black
        args: [--config=backend/pyproject.toml, --check, --diff, backend/]
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
        name: flake8
        language: system
        entry: flake8
        additional_dependencies: ["flake8-bugbear==19.3.0", "flake8-django==0.0.4", "flake8-docstrings==1.3.1", "pylint-django==2.0.11"]
        args: [--config=backend/tox.ini, backend]
        types: [python]
```

**Comment by asottile** [comment] 2019-08-06 13:44
Why do you need to cd?

**Comment by asottile** [comment] 2019-08-06 13:47
Also you probably shouldn't use `language` in that way, it defeats the point of the framework. You can delete `name`, `language`, `entry`, and `types` keys

**Comment by imomaliev** [comment] 2019-08-06 16:21
@asottile For some reason when flake8 is run from root dir and not from backend, config file `tox.ini` doesn't get picked up correctly for `per-file-ignores`

```
[flake8]
max-line-length = 100
exclude =
    # No need to traverse our venv directory
    .venv,
    # No need to traverse our pytest directory
    .pytest_cache,
    # There's no value in checking cache directories
    __pycache__,
    # TODO: remove this after new flake8 release
    */migrations/*.py
ignore = 
    # for black
    # line too long (82 > 79 characters)
    E501,
    # for black
    # line break before binary operator
    W503,
    # missing docstrings group
    D10,
per-file-ignores =
    src/project/settings/*.py:F401,F403,F405
    tests/settings.py:F401,F403

```

**Comment by asottile** [comment] 2019-08-06 16:25
ah yeah that's a bug in flake8 which is being worked on for the 3.8.x release of flake8 -- you can follow that here: https://gitlab.com/pycqa/flake8/issues/517

in the meantime you can put `*/` on the beginning of your paths

**Comment by asottile** [comment] 2019-08-06 16:26
I'd also suggest using `extend-ignore` over `ignore` in the flake8 conf and you can usually drop the `exclude=` setting if you're invoking `flake8` through `pre-commit` (as pre-commit will only ever consider your checked in files)

**Comment by imomaliev** [comment] 2019-08-07 04:48
@asottile Thanks for suggestions. I need exclude for my CI configuration. Don't you think that it would be useful feature to have configuration for `workdir`? many scripts require you to run them from the root of the folder

**Comment by asottile** [comment] 2019-08-07 04:52
no I don't want to support that -- it rarely comes up and in most cases it's already a hack and worst case you can wrap whatever tool in `entry: bash -c 'cd ... && ... "$@"' --`

there's a slippery slope of things that _could_ be supported. adding support for every wacky `cd` / `env` / etc. under the sun is not on the table, especially when it's very very standard approach: to run with the current environment in the root of the repository.

there's a quote that I don't know where I'm stealing from and I don't know the exact phrasing but it goes something like "In open source, no is temporary but yes is forever" -- I really don't want to add yet more edge cases for things I will never ever use and can barely explain how the rules for such a thing would work.

**Closed by asottile** 2019-08-07 04:52 UTC
Labels: question

**Comment by patrick91** [comment] 2019-08-28 21:51
@asottile I had to do something a bit hacky to support `entry: bash -c 'cd ... && ... "$@"'`. My use case is that I want to use eslint without having to install dependencies twice, I'm also running in a monorepo setup, similar to the one in the first comment. We have a frontend folder with all the configuration for eslint and running eslint from outside the frontend folder has been a bit tricky, for example it would ignore the .eslintignore file. Also using the bash hack didn't work as pre-commit passes the path with `frontend/`, so the file wasn't being found. For now I've solved using a custom script that fixes the paths, but I don't really like it :)

Do you have a better suggestion? 

Here's the hack I did, for more context: https://github.com/pythonitalia/pycon/pull/808/commits/f623cf87bc235bcfab07fbad0eed7d119fa971e1

**Comment by asottile** [comment] 2019-08-28 22:57
ah right yeah since pre-commit will send paths from the root of the repository -- that's probably how I would do it as well (though maybe with path joining functions instead of substrings, but same deal either way) :+1:

**Comment by alessandro308** [comment] 2019-10-30 09:54
I tried the approach suggested here but I receive:
`Executable '/Users/alessandro/repos/repo-name/bash' not found` 

Any idea how to fix?

**Comment by alessandro308** [comment] 2019-10-30 09:58
Fixed using `language: system` instead of `language: script`

**Comment by sjdemartini** [comment] 2020-12-18 01:38
For anyone who comes across this later, I based my approach on what patrick91 did (thanks for the tips!), but noticed that the approach with `entry: bash -c 'cd ... && ... "$@"'` (i.e., passing the file names along with bash via `$@`) actually ends up dropping the first filename and doesn't send the complete list. For me, rather than:

```yaml
entry: bash -c 'cd frontend && yarn precommit-lint "$@"'
```

This worked instead:
```yaml
entry: yarn --cwd frontend precommit-lint
```

**Comment by brendanlong** [comment] 2021-05-18 20:25
I think having an option for changing the CWD is valuable and common enough to be worth adding an option for it. We use pre-commit in a monorepo and not all tools have a `--cwd` argument :(

**Comment by brendanlong** [comment] 2021-05-18 20:29
I see a bunch of comments by @asottile closing issues and linking to other closed issues. Is there a single place to discuss this / a single place describing why the maintainers aren't willing to support this use-case?

**Comment by asottile** [comment] 2021-05-18 21:13
@brendanlong the reasoning is here: https://github.com/pre-commit/pre-commit/issues/1110#issuecomment-518939116

**Comment by brendanlong** [comment] 2021-05-18 21:24
I see :( I'd argue that having so many people open the same issue is an indication that this isn't a rare use-case, but I guess you've already decided.

**Comment by asottile** [comment] 2021-05-18 21:32
correct

and the feature that's being requested has a very easy workaround, and implementing it in-framework would be very very difficult to do correctly and would open up a slippery slope of other similarly niche features.  additionally, the feature that's being asked for is *intentionally* outside of what is supported, there is only one "git hooks" per repository so trying to support sub-repos is just not feasible, and attempting to do so will lead to a lot of complexity that I don't want to support.  and the "so many" is like 5? 6? if I implemented every feature that 5 or 6 people asked for I'd have an unmaintainable mess and there would be no project.

perhaps if your company sustainably sponsored and supported the project I could rationalize supporting such a thing

**Comment by dpinol** [comment] 2021-05-19 09:22
Monorepos are here to stay. Adding a "cwd" field would make the yaml much simpler (without requiring bash with quotes, or calling external scripts). Any volunteer to give it a stab?

thank you for supporting this wonderful tool!

**Comment by asottile** [comment] 2021-05-19 15:24
> Any volunteer to give it a stab?

please don't, any such contribution would not be welcome without funding maintenance of such a feature as I've already said no.  the issue isn't about implementing and accepting, it's about long term complexity and maintenance

**Comment by MatthewScholefield** [comment] 2021-06-27 01:56
For people that need pre-commit hooks inside a mono-repo, I found [this alternative called Mookme](https://github.com/Escape-Technologies/mookme) built specifically for this situation. I noticed it from [the author's post on reddit](https://www.reddit.com/r/git/comments/n9ad2t/our_tool_for_handling_git_hooks_on_monorepos/).

**Comment by SebastianoF** [comment] 2021-09-17 18:14
Much better keep the code simple and functional than having too many messy and half working functionalities. So kudos to not add any extra feature on request.

Here is my work-around for a monorepo where there are two libraries `my_monorepo/library1` and `my_monorepo/library2`, as in:

```
my_monorepo
├── README.md
├── .gitlab-ci.yml
├── library1
│   ├── setup.py
│   ├── pyproject.toml
│   ├── src
│   ├── tests
│   └── .pre-commit-config.yaml
├── library2
│   ├── setup.py
│   ├── pyproject.toml
│   ├── src
│   ├── tests
│   └── .pre-commit-config.yaml
```


1. Create a Makefile at the root level `my_monorepo` with
```bash
# Makefile
pre-commit:
	cd library1 && pre-commit run --files ./*
	cd library2 && pre-commit run --files ./*

pre-commit-install:
	cd library1 && pre-commit install --allow-missing-config
	cd library2 && pre-commit install --allow-missing-config

pre-commit-uninstall:
	cd rule_interpreter && pre-commit uninstall
	cd rule_creator && pre-commit uninstall
```

2. Then:
- To run pre-commit from the source folder run: `make pre-commit`.
- To install the hooks run: `make pre-commit-install`.
- To uninstall the hooks run: `make pre-commit-uninstall`.


Does it work?

 Only `make pre-commit` works 👎 !
 
Since the hook name can not be specified, the last pre-commit install command (for library2) overwrites the previous one (library1) at `.git/hooks/pre-commit`


Here is the crazy idea:

How difficult would it be to specify the name of the hook with an extra flag (e.g. `--name`) when installing and uninstalling?

This would allow the above Makefile to work, simply adding the flag `--name`, as in:

```bash
# Makefile
pre-commit:
	cd library1 && pre-commit run --files ./*
	cd library2 && pre-commit run --files ./*

pre-commit-install:
	cd library1 && pre-commit install --allow-missing-config --name library1
	cd library2 && pre-commit install --allow-missing-config --name library2

pre-commit-uninstall:
	cd rule_interpreter && pre-commit uninstall --name library1
	cd rule_creator && pre-commit uninstall --name library2
```

So that two hooks are created:

```bash
$ ls .git/hooks/
pre-commit-library1
pre-commit-library2
```

As far as I can see it would not be mortally complicated to implement, and the maintenance would also be straightforward.

I may even give it a try if you give me green light. Otherwise no issue. What said above sill holds.

**Comment by MatthewScholefield** [comment] 2021-09-17 18:33
@asottile Is it alright if I share a project that solves this for the 5 or 6 users who have this problem?

As I understand you've decided not to support this within pre-commit which totally makes sense, which is why I thought it'd be helpful to share here.
