### ISSUE TITLE
Found pre-commit 0.1 version

### ISSUE THREAD

**Issue by mitzkia** [pre-commit/pre-commit#1059] opened 2019-06-16 06:11 UTC
Hi, 

This is the second time when I can not commit because of the following error message:
```console
micek@tristram ~/n/g/g/s/t/python_functional> git commit -a
[ERROR] The hook `reorder-python-imports` requires pre-commit version 0.15.0 but version 0.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.
```

Until now I can not debug the root cause, could you please help me in that?
I assume that it is connected somehow with my SHELL or PATH setup.
Note:
Create a new terminal SHELL did not help.
I do the following debug:
```console
micek@tristram ~/n/g/g/s/t/python_functional> python3 -m pip list | grep pre-commit
pre-commit                    1.17.0     
pre-commit-hooks              2.2.3      
micek@tristram ~/n/g/g/s/t/python_functional> python -m pip list | grep pre-commit
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
micek@tristram ~/n/g/g/s/t/python_functional> which pre-commit
/usr/local/bin/pre-commit
micek@tristram ~/n/g/g/s/t/python_functional> pre-commit --version
pre-commit 0.1
micek@tristram ~/n/g/g/s/t/python_functional> sudo -H pre-commit --version
[sudo] password for micek: 
pre-commit 1.17.0
micek@tristram ~/n/g/g/s/t/python_functional> /usr/local/bin/pre-commit --version
pre-commit 0.1
micek@tristram ~/n/g/g/s/t/python_functional> sudo -H /usr/local/bin/pre-commit --version
pre-commit 1.17.0
micek@tristram ~/n/g/g/s/t/python_functional> env
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEFAULTS_PATH=/usr/share/gconf/i3.default.path
DESKTOP_SESSION=i3
DISPLAY=:0
GDMSESSION=i3
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/d3158ea7_52fa_42b2_b894_749dd49a09a3
GNOME_TERMINAL_SERVICE=:1.313
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK_MODULES=gail:atk-bridge
HOME=/home/micek
LANG=en_US.UTF-8
LC_ADDRESS=hu_HU.UTF-8
LC_IDENTIFICATION=hu_HU.UTF-8
LC_MEASUREMENT=hu_HU.UTF-8
LC_MONETARY=hu_HU.UTF-8
LC_NAME=hu_HU.UTF-8
LC_NUMERIC=hu_HU.UTF-8
LC_PAPER=hu_HU.UTF-8
LC_TELEPHONE=hu_HU.UTF-8
LC_TIME=hu_HU.UTF-8
LOGNAME=micek
MANDATORY_PATH=/usr/share/gconf/i3.mandatory.path
PATH=/home/micek/.cargo/bin:/home/micek/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/micek/na_akkor_ujra/git-projects/github_mitzkia/syslog-ng/tests/python_functional
QT_ACCESSIBILITY=1
SHELL=/usr/bin/fish
SHLVL=1
SSH_AGENT_PID=2072
SSH_AUTH_SOCK=/tmp/ssh-goSNVV1lXZmB/agent.1990
TERM=xterm-256color
USER=micek
USERNAME=micek
VTE_VERSION=5202
WINDOWPATH=2
XAUTHORITY=/run/user/1000/gdm/Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-i3:/etc/xdg
XDG_CURRENT_DESKTOP=i3
XDG_DATA_DIRS=/usr/share/i3:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=i3
XDG_SESSION_ID=2
XDG_SESSION_TYPE=x11
XDG_VTNR=2
micek@tristram ~/n/g/g/s/t/python_functional> cat /usr/local/bin/pre-commit
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys

from pre_commit.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
micek@tristram ~/n/g/g/s/t/python_functional> whereis pre-commit
pre-commit: /usr/local/bin/pre-commit
```

**Comment by mitzkia** [comment] 2019-06-16 09:28
* Restarting the host did not help.
* Reinstalling pre-commit package (from pip) did not help.

**Comment by mitzkia** [comment] 2019-06-16 09:32
When I install pre-commit for the user it works
```console
micek@tristram ~> python3 -m pip uninstall pre-commit
Uninstalling pre-commit-1.17.0:
  Would remove:
    /home/micek/.local/bin/pre-commit
    /home/micek/.local/bin/pre-commit-validate-config
    /home/micek/.local/bin/pre-commit-validate-manifest
    /home/micek/.local/lib/python3.6/site-packages/pre_commit-1.17.0.dist-info/*
    /home/micek/.local/lib/python3.6/site-packages/pre_commit/*
Proceed (y/n)? y
  Successfully uninstalled pre-commit-1.17.0
micek@tristram ~> pre-commit

Command 'pre-commit' not found, but can be installed with:

sudo snap install pre-commit

micek@tristram ~> python3 -m pip install --user -U pre-commit
Collecting pre-commit
  Using cached https://files.pythonhosted.org/packages/59/22/13e65062888c1f53619ef557f885817874aabc447e1cbb4cf774ceaf222f/pre_commit-1.17.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: cfgv>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (2.0.0)
Requirement already satisfied, skipping upgrade: nodeenv>=0.11.1 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.3.3)
Requirement already satisfied, skipping upgrade: identify>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.4.1)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.12.0)
Requirement already satisfied, skipping upgrade: virtualenv>=15.2 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (16.6.0)
Requirement already satisfied, skipping upgrade: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from pre-commit) (0.18)
Requirement already satisfied, skipping upgrade: importlib-resources; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.0.2)
Requirement already satisfied, skipping upgrade: toml in /usr/local/lib/python3.6/dist-packages (from pre-commit) (0.10.0)
Requirement already satisfied, skipping upgrade: aspy.yaml in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.2.0)
Requirement already satisfied, skipping upgrade: pyyaml in /usr/lib/python3/dist-packages (from pre-commit) (3.12)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->pre-commit) (0.5.1)
Installing collected packages: pre-commit
Successfully installed pre-commit-1.17.0
micek@tristram ~> pre-commit --version
pre-commit 1.17.0
```

**Comment by asottile** [comment] 2019-06-16 14:20
I've seen this happen when there's mysteriously two copies of pre-commit installed (usually one accidentally via `easy_install`) -- often `pip uninstall pre-commit` (three times in a row to make sure it's gone) can help -- but sometimes you have to manually track down the other install (especially if it was done via easy_install) via something like:

```bash
find /usr/local ~/.local -name "*pre_commit*"
```

**Comment by mitzkia** [comment] 2019-06-16 15:11
Thanks for helping.
Luckily for now I have a fix reproduction (installing back pre-commit with sudo).

So as you requested, this is the current state on my machine:
 * you can see the "good" installation for the user (pip install --user)
 * the uninstallation
 * the installation back with root
 * the query of the pre-commit instances
```console
micek@tristram ~> find /usr/local ~/.local -name "*pre_commit*"
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks-2.2.3.dist-info
/home/micek/.local/lib/python3.6/site-packages/pre_commit
/home/micek/.local/lib/python3.6/site-packages/pre_commit/resources/empty_template_pre_commit_dummy_package.gemspec
/home/micek/.local/lib/python3.6/site-packages/pre_commit-1.17.0.dist-info
micek@tristram ~> pre-commit --version
pre-commit 1.17.0
micek@tristram ~> python3 -m pip uninstall pre-commit
Uninstalling pre-commit-1.17.0:
  Would remove:
    /home/micek/.local/bin/pre-commit
    /home/micek/.local/bin/pre-commit-validate-config
    /home/micek/.local/bin/pre-commit-validate-manifest
    /home/micek/.local/lib/python3.6/site-packages/pre_commit-1.17.0.dist-info/*
    /home/micek/.local/lib/python3.6/site-packages/pre_commit/*
Proceed (y/n)? y
  Successfully uninstalled pre-commit-1.17.0
micek@tristram ~> pre-commit --version

Command 'pre-commit' not found, but can be installed with:

sudo snap install pre-commit

micek@tristram ~> find /usr/local ~/.local -name "*pre_commit*"
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks-2.2.3.dist-info
micek@tristram ~> sudo python3 -m pip install -U pre-commit
[sudo] password for micek: 
WARNING: The directory '/home/micek/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/micek/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pre-commit
  Downloading https://files.pythonhosted.org/packages/59/22/13e65062888c1f53619ef557f885817874aabc447e1cbb4cf774ceaf222f/pre_commit-1.17.0-py2.py3-none-any.whl (153kB)
     |████████████████████████████████| 153kB 511kB/s 
Requirement already satisfied, skipping upgrade: pyyaml in /usr/lib/python3/dist-packages (from pre-commit) (3.12)
Requirement already satisfied, skipping upgrade: virtualenv>=15.2 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (16.6.0)
Requirement already satisfied, skipping upgrade: cfgv>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (2.0.0)
Requirement already satisfied, skipping upgrade: nodeenv>=0.11.1 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.3.3)
Requirement already satisfied, skipping upgrade: importlib-resources; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.0.2)
Requirement already satisfied, skipping upgrade: aspy.yaml in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.2.0)
Requirement already satisfied, skipping upgrade: toml in /usr/local/lib/python3.6/dist-packages (from pre-commit) (0.10.0)
Requirement already satisfied, skipping upgrade: importlib-metadata in /usr/local/lib/python3.6/dist-packages (from pre-commit) (0.18)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.12.0)
Requirement already satisfied, skipping upgrade: identify>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from pre-commit) (1.4.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata->pre-commit) (0.5.1)
Installing collected packages: pre-commit
Successfully installed pre-commit-1.17.0
micek@tristram ~> pre-commit --version
pre-commit 0.1
micek@tristram ~> find /usr/local ~/.local -name "*pre_commit*"
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks
/usr/local/lib/python3.6/dist-packages/pre_commit
/usr/local/lib/python3.6/dist-packages/pre_commit/resources/empty_template_pre_commit_dummy_package.gemspec
/usr/local/lib/python3.6/dist-packages/pre_commit-1.17.0.dist-info
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks-2.2.3.dist-info
```

**Comment by mitzkia** [comment] 2019-06-16 15:16
I did not know, could you identify a second copy on my machine? I did not notice it.

**Comment by asottile** [comment] 2019-06-16 15:20
I wonder what happens if you do this (paste this verbatim into your terminal)

```bash
$(head -1 $(which pre-commit) | cut -d'!' -f2) -c 'import importlib_metadata; print(vars(importlib_metadata.distribution("pre-commit")))'
```

and maybe expand the `find` command to:

```
find /usr ~/.local -name "*commit*"
```

to uninstall for sure, try running this **three times** each (using `pre-commit --version` isn't a surefire way to ensure it is uninstalled):

```
pip uninstall pre-commit
sudo python3 -m pip uninstall pre-commit
```

not sure if it's maybe installed into `/usr` as well and maybe named `pre-commit` instead of `pre_commit`

I'm actually surprised that the `0.1` information is coming from somewhere, pre-commit didn't even support `--version` until `0.2.0`

**Comment by mitzkia** [comment] 2019-06-16 15:33
Thanks again. 

Here is my output
```console
micek@tristram:~$ $(head -1 $(which pre-commit) | cut -d'!' -f2) -c 'import importlib_metadata; print(vars(importlib_metadata.distribution("pre-commit")))'
{'_path': Path('/home/micek/.local/lib/python3.6/site-packages/ez_git-0.1-py3.6.egg', 'EGG-INFO/')}
micek@tristram:~$ find /usr ~/.local -name "*commit*"
/usr/share/git-gui/lib/commit.tcl
/usr/share/vim/vim80/syntax/hgcommit.vim
/usr/share/vim/vim80/syntax/gitcommit.vim
/usr/share/vim/vim80/ftplugin/hgcommit.vim
/usr/share/vim/vim80/ftplugin/gitcommit.vim
/usr/share/meld/icons/vc-commit-24.png
/usr/share/doc/nmap/committers.txt.gz
/usr/share/doc/git/contrib/coccinelle/commit.cocci
/usr/share/code/resources/app/extensions/git/languages/git-commit.language-configuration.json
/usr/share/code/resources/app/extensions/git/syntaxes/git-commit.tmLanguage.json
/usr/share/man/man8/systemd-machine-id-commit.service.8.gz
/usr/share/man/man1/debcommit.1.gz
/usr/share/man/man1/git-commit-tree.1.gz
/usr/share/man/man1/git-verify-commit.1.gz
/usr/share/man/man1/git-get-tar-commit-id.1.gz
/usr/share/man/man1/docker-commit.1.gz
/usr/share/man/man1/git-commit-graph.1.gz
/usr/share/man/man1/git-commit.1.gz
/usr/share/man/man1/docker-container-commit.1.gz
/usr/share/man/de/man1/debcommit.1.gz
/usr/share/man/fr/man1/debcommit.1.gz
/usr/share/git-core/templates/hooks/commit-msg.sample
/usr/share/git-core/templates/hooks/pre-commit.sample
/usr/share/git-core/templates/hooks/prepare-commit-msg.sample
/usr/share/ibus-table/icons/ncommit.svg
/usr/share/ibus-table/icons/acommit.svg
/usr/local/bin/no-commit-to-branch
/usr/local/bin/pre-commit-validate-config
/usr/local/bin/pre-commit-validate-manifest
/usr/local/bin/pre-commit
/usr/local/lib/python2.7/dist-packages/kafka/protocol/commit.pyc
/usr/local/lib/python2.7/dist-packages/kafka/protocol/commit.py
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks/__pycache__/no_commit_to_branch.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks/no_commit_to_branch.py
/usr/local/lib/python3.6/dist-packages/pre_commit
/usr/local/lib/python3.6/dist-packages/pre_commit/resources/empty_template_pre_commit_dummy_package.gemspec
/usr/local/lib/python3.6/dist-packages/pre_commit-1.17.0.dist-info
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/ls_tree_commit
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/rev_list_commit_idabbrev
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/rev_list_commit_diffs
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/show_empty_commit
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/commit_with_gpgsig
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/rev_list_commit_stats
/usr/local/lib/python3.6/dist-packages/git/test/fixtures/commit_invalid_data
/usr/local/lib/python3.6/dist-packages/git/test/test_commit.py
/usr/local/lib/python3.6/dist-packages/git/test/performance/test_commit.py
/usr/local/lib/python3.6/dist-packages/git/objects/__pycache__/commit.cpython-36.pyc
/usr/local/lib/python3.6/dist-packages/git/objects/commit.py
/usr/local/lib/python3.6/dist-packages/pre_commit_hooks-2.2.3.dist-info
/usr/bin/debcommit
/usr/lib/git-core/git-commit-tree
/usr/lib/git-core/git-commit-graph
/usr/lib/git-core/git-commit
/usr/lib/git-core/git-get-tar-commit-id
/usr/lib/git-core/git-verify-commit
/home/micek/.local/share/fish/generated_completions/git-commit-tree.fish
/home/micek/.local/share/fish/generated_completions/debcommit.fish
/home/micek/.local/share/fish/generated_completions/docker-commit.fish
/home/micek/.local/share/fish/generated_completions/docker-container-commit.fish
/home/micek/.local/share/fish/generated_completions/git-commit.fish
/home/micek/.local/share/fish/generated_completions/git-verify-commit.fish
/home/micek/.local/share/fish/generated_completions/git-commit-graph.fish
```

I will continue with the uninstallation  (3 times)

**Comment by mitzkia** [comment] 2019-06-16 15:40
Ohh, as you can see there is a "reference" for ez-git, this is my side-project, maybe it causes the issue...
I will check it asap.

**Comment by mitzkia** [comment] 2019-06-16 15:52
Sorry, it was totally my fault. I have played with installing my own python projects via setup.py build/install (setup.cfg was filled -> maybe in wrong way). After removing project contents from ~/.local/lib/ it works

```console
micek@tristram:~/na_akkor_ujra/git-projects/github_mitzkia/ez-git$ $(head -1 $(which pre-commit) | cut -d'!' -f2) -c 'import importlib_metadata; print(vars(importlib_metadata.distribution("pre-commit")))'
{'_path': PosixPath('/usr/local/lib/python3.6/dist-packages/pre_commit-1.17.0.dist-info')}
micek@tristram:~/na_akkor_ujra/git-projects/github_mitzkia/ez-git$ pre-commit --version
pre-commit 1.17.0
```

But not yet understand how this projects could conflicts with pre-commit.
Sorry again.

**Comment by asottile** [comment] 2019-06-16 16:19
Weird, somehow that egg was being identified as pre-commit

If you could reproduce that I would be interested in the setup.py and commands that led to that, I suspect there's maybe something to fix in importlib-metadata

**Comment by mitzkia** [comment] 2019-06-16 17:24
Hi,
I could create a Dockerfile for a reproduction. Hope it helps.


```
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y python3-pip python3-setuptools nano
RUN python3 -m pip install  pre-commit
RUN pre-commit --version
RUN mkdir test/
RUN echo "[metadata]" >> test/setup.cfg
RUN echo "name = ez_git" >> test/setup.cfg
RUN echo "version = 0.1" >> test/setup.cfg
RUN echo "from setuptools import setup" >> test/setup.py
RUN echo "setup()" >> test/setup.py
RUN cd test ; python3 setup.py install --user
RUN pre-commit --version
```

my docker build output
```
Sending build context to Docker daemon  2.048kB
Step 1/13 : FROM ubuntu:latest
 ---> 7698f282e524
Step 2/13 : RUN apt-get update
 ---> Using cache
 ---> cea2fec21b94
Step 3/13 : RUN apt-get install -y python3-pip python3-setuptools nano
 ---> Using cache
 ---> 08e6a0760bd4
Step 4/13 : RUN python3 -m pip install  pre-commit
 ---> Using cache
 ---> 9479ad43c4fe
Step 5/13 : RUN pre-commit --version
 ---> Using cache
 ---> 082729569076
Step 6/13 : RUN mkdir test/
 ---> Using cache
 ---> 41bde4bb0640
Step 7/13 : RUN echo "[metadata]" >> test/setup.cfg
 ---> Using cache
 ---> fecc1db31f82
Step 8/13 : RUN echo "name = ez_git" >> test/setup.cfg
 ---> Using cache
 ---> 136ffe38a6a6
Step 9/13 : RUN echo "version = 0.1" >> test/setup.cfg
 ---> Using cache
 ---> 34a7365959b6
Step 10/13 : RUN echo "from setuptools import setup" >> test/setup.py
 ---> Using cache
 ---> fbac5510275f
Step 11/13 : RUN echo "setup()" >> test/setup.py
 ---> Using cache
 ---> ca42016f2296
Step 12/13 : RUN cd test ; python3 setup.py install --user
 ---> Running in 3569be53c636
running install
running bdist_egg
running egg_info
creating ez_git.egg-info
writing ez_git.egg-info/PKG-INFO
writing dependency_links to ez_git.egg-info/dependency_links.txt
writing top-level names to ez_git.egg-info/top_level.txt
writing manifest file 'ez_git.egg-info/SOURCES.txt'
reading manifest file 'ez_git.egg-info/SOURCES.txt'
writing manifest file 'ez_git.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ez_git.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ez_git.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ez_git.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ez_git.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/ez_git-0.1-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ez_git-0.1-py3.6.egg
Copying ez_git-0.1-py3.6.egg to /root/.local/lib/python3.6/site-packages
Adding ez-git 0.1 to easy-install.pth file

Installed /root/.local/lib/python3.6/site-packages/ez_git-0.1-py3.6.egg
Processing dependencies for ez-git==0.1
Finished processing dependencies for ez-git==0.1
Removing intermediate container 3569be53c636
 ---> 936432d1b1b5
Step 13/13 : RUN pre-commit --version
 ---> Running in 5529f3ec7257
pre-commit 0.1
Removing intermediate container 5529f3ec7257
 ---> c3df3f9021d4
Successfully built c3df3f9021d4
Successfully tagged pre_commit:latest
```

**Comment by asottile** [comment] 2019-06-16 19:30
Awesome! Thank you for the reproduction, I'll see what I can do to fix this 👍

**Comment by asottile** [comment] 2019-06-18 04:41
https://gitlab.com/python-devs/importlib_metadata/merge_requests/78 should address that -- or whatever comes out of that patch (it's not my best work for sure 😢 -- eggs are sadness)

I'm going to close this since I've successfully triaged this, hopefully we'll get a fix in there 👍

**Closed by asottile** 2019-06-18 04:41 UTC
Labels: question, upstream-bug
