### ISSUE TITLE
different results between pre-commit run and git commit

### ISSUE THREAD

**Issue by jbigatti** [pre-commit/pre-commit#818] opened 2018-08-24 12:26 UTC
I'm having different output:
if I run `pre-commit run --files path/to/file.py`, I get
```
Flake8...................................................................Passed
Debug Statements (Python)................................................Passed
isort....................................................................Passed
Verifying PEP257 Compliance..............................................Passed
```
but if I use `git commit path/to/file.py`, I get
```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/<my_user>/.cache/pre-commit/patch1535954836.
Flake8...................................................................Passed
Debug Statements (Python)................................................Passed
isort....................................................................Passed
Verifying PEP257 Compliance..............................................Failed
hookid: pydocstyle

path/to/file.py:1 at module level:
        D100: Missing docstring in public module

[INFO] Restored changes from /home/<my_user>/.cache/pre-commit/patch1535954836.
```
My config file:
```
exclude: '^$'
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    - id: flake8
      args: [--config=setup.cfg]
      language_version: python3
    - id: debug-statements
      language_version: python3
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4 
    hooks:
    - id: isort
      args: [--check-only]
      language_version: python3
-   repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1 
    hooks:
    - id: pydocstyle
      language_version: python3
```
My setup.cfg file has:
```
[pydocstyle]
ignore=D100,D104,D105,D202,D203,D209
```

I'm using
- pyenv 1.2.6
- Ubuntu 16.04
- git 2.7.4

Am I missing something or doing something wrong?

**Comment by asottile** [comment] 2018-08-24 13:01
Hmm that's odd, it's stressing the file? Can you provide `git diff` before you run that command?

**Comment by asottile** [comment] 2018-08-24 14:53
oh I bet I know what's happening here!

Here's how I can demonstrate your exact reproduction:

## Step 1: add and commit these

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
    rev: v2.1.1 
    hooks:
    - id: pydocstyle
```

### setup.cfg

```ini
[pydocstyle]
ignore=
```

### mymod.py

```python
"""A very good docstring."""
```

## Step 2: Modify the contents to look like this *but do not stage them*

### setup.cfg

```ini
[pydocstyle]
ignore=D100
```

### mymod.py

```python
def f():
    pass
```

If you run `git diff` it should look like this:

```diff
diff --git a/mymod.py b/mymod.py
index 0c8cd5a..4f28bc7 100644
--- a/mymod.py
+++ b/mymod.py
@@ -1 +1,2 @@
-"""A very good docstring."""
+def f():
+    pass
diff --git a/setup.cfg b/setup.cfg
index d88917d..56565bf 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,2 +1,2 @@
 [pydocstyle]
-ignore=
+ignore=D100,D103
```

## Step 3: commit just `mymod.py`

```console
$ git commit mymod.py
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/asottile/.cache/pre-commit/patch1535122114.
Verifying PEP257 Compliance..............................................Failed
hookid: pydocstyle

mymod.py:1 at module level:
        D100: Missing docstring in public module
mymod.py:1 in public function `f`:
        D103: Missing docstring in public function

[INFO] Restored changes from /home/asottile/.cache/pre-commit/patch1535122114.
```

This _is_ working as intended, here's what's happening:

1. `git commit mymod.py` will *only* commit `mymod.py` and not other files in the working directory
2. `pre-commit` knows this, and so it sets the state of the checkout to that of what's being committed.  In this case, it temporarily undoes the changes to `setup.cfg` (you can verify this by peeking at th epatch file it creates):

    ```diff
    $ cat /home/asottile/.cache/pre-commit/patch1535122114
    diff --git a/setup.cfg b/setup.cfg
    index d88917d..56565bf 100644
    --- a/setup.cfg
    +++ b/setup.cfg
    @@ -1,2 +1,2 @@
     [pydocstyle]
    -ignore=
    +ignore=D100,D103
    ```
3. then the commit fails!

If that commit were to succeed (which many other frameworks get wrong) you'd have a commit which _fails_ linting being committed! (which is kind of the point of `pre-commit` to prevent!).  In your case, make sure to `git commit setup.cfg path/to/file.py` and you should be good to go :)

Note that the actual `git` hook just invokes `pre-commit run` (usually with no arguments) and not `pre-commit run --files ...`.  `pre-commit run --files ...` is a convenience helper for commandline usage and avoids stashing.

## bonus Step 4: commit both files at once

```console
$ git commit -m 'change!' mymod.py setup.cfg 
Verifying PEP257 Compliance..............................................Passed
[master f38958b] change!
 2 files changed, 3 insertions(+), 2 deletions(-)
```

**Comment by jbigatti** [comment] 2018-08-24 15:58
Excellent!. I was writing the same thing and my last answer was exactly that: Is this an expected behavior?

Thanks!

**Comment by asottile** [comment] 2018-08-24 15:59
Yep totally expected! Don't want to commit things that are broken :)

Thanks for the issue :)

**Closed by asottile** 2018-08-24 15:59 UTC
Labels: question
