### ISSUE TITLE
quiet mode

### ISSUE THREAD

**Issue by blueyed** [pre-commit/pre-commit#957] opened 2019-02-28 17:44 UTC
pre-commit is rather verbose.

With pytest's repo:

```
% git commit -m foo
black................................................(no files to check)Skipped
blacken-docs.........................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)............................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
Reorder python imports...............................(no files to check)Skipped
pyupgrade............................................(no files to check)Skipped
rst ``code`` is two backticks........................(no files to check)Skipped
rst..................................................(no files to check)Skipped
changelog filenames..................................(no files to check)Skipped
py library is deprecated.............................(no files to check)Skipped
[revisit-cov 8293f3ff] foo
 1 file changed, 5 insertions(+)
```

I would like it to only output anything in case of issues, but being quiet otherwise - maybe a single line would be good to see that it is running though ("Running pre-commit... ok.")

There appears to only be an option to make it more verbose even: https://github.com/pre-commit/pre-commit/blob/518a72d7e7598b71105fb764d990438c1b6d485a/pre_commit/main.py#L62

I think `-q` should be added, and decrement from `-v` - and then `-qq` would not display the single "Running pre-committ... ok." line.

**Comment by asottile** [comment] 2019-02-28 17:45
Duplicate of #823

**Closed by asottile** 2019-02-28 17:45 UTC

**Comment by blueyed** [comment] 2019-02-28 17:47
Oh, sorry for missing it - re-open then?
