### ISSUE TITLE
Pre-push handles only the first branch if multiple branches is pushed with "git push --all"

### ISSUE THREAD

**Issue by kim-groenborg-nielsen** [pre-commit/pre-commit#1940] opened 2021-06-12 16:15 UTC
When I have multiple unpushed branches and I want to push all with "git push --all", then it is only the first branch that is parsed to the pre-push plugin.

I think it can be solved by returning Optional[List[argparse.Namespace]] from _pre_push_ns method in hook_impl.py and then loop through the list in hook_impl method.

**Comment by asottile** [comment] 2021-06-12 16:41
this is a duplicate of #1908 -- unfortunately multiple branches isn't really solvable

**Closed by asottile** 2021-06-12 16:41 UTC
