### ISSUE TITLE
SSLError on conda and Windows 10

### ISSUE THREAD

**Issue by ltbd78** [pre-commit/pre-commit#2445] opened 2022-07-08 00:44 UTC
### search tried in the issue tracker

sslerror

### describe your issue

Windows 10
Python Version: 3.8.0
Conda Version: 4.12.0
Path Environment Variables:
  - C:\ProgramData\Miniconda3\
  - C:\ProgramData\Miniconda3\Scripts
  - C:\ProgramData\Miniconda3\Library\bin

Error:
Running `pre-commit` in my conda environment throws SSLError.

Have tried:
 - `pip install pre-commit`
 - `conda install -c conda-forge pre-commit`
 - installing older version of pre-commit
 - reinstalled Git-SCM
 - rebooted

### pre-commit --version

2.19.9

### .pre-commit-config.yaml

```yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
```

### version information

```
pre-commit version: 2.19.0
git --version: git version 2.37.0.windows.1
sys.version:
    3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
sys.executable: C:\Users\Linsu Han\.conda\envs\bot\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Linsu Han\\.cache\\pre-commit\\repo34bmz8l8\\py_env-default\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\linsu han\.cache\pre-commit\repo34bmz8l8
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Could not fetch URL https://pypi.org/simple/ruamel-yaml/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ruamel-yaml/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
    
stderr:
    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    ERROR: Could not find a version that satisfies the requirement ruamel.yaml>=0.15 (from pre-commit-hooks) (from versions: none)
    ERROR: No matching distribution found for ruamel.yaml>=0.15
    
```

```
Traceback (most recent call last):
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\main.py", line 389, in main
    return run(args.config, store, args)
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\commands\run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\repository.py", line 79, in _hook_install
    lang.install_environment(
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\languages\python.py", line 221, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\languages\helpers.py", line 51, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\Linsu Han\.conda\envs\bot\lib\site-packages\pre_commit\util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Linsu Han\\.cache\\pre-commit\\repo34bmz8l8\\py_env-default\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\linsu han\.cache\pre-commit\repo34bmz8l8
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Could not fetch URL https://pypi.org/simple/ruamel-yaml/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ruamel-yaml/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
    
stderr:
    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ruamel-yaml/
    ERROR: Could not find a version that satisfies the requirement ruamel.yaml>=0.15 (from pre-commit-hooks) (from versions: none)
    ERROR: No matching distribution found for ruamel.yaml>=0.15
```

**Comment by asottile** [comment] 2022-07-08 02:13
looks like an exact duplicate of #1283 -- either way not a pre-commit issue (I found this by searching sslerror?)

**Closed by asottile** 2022-07-08 02:13 UTC

**Comment by ltbd78** [comment] 2022-07-08 22:10
Update: I managed to magically fix this by:
    1. Deleting the Miniconda paths
    2. Deleting and recreating my conda environment

**Comment by ChengguiSun** [comment] 2022-11-14 17:41
> 

Hello, I encountered the same error. Tried "deleting and recreating conda environment", and it didn't work.
