### ISSUE TITLE
Don't lint broken symlinks

### ISSUE THREAD

**Issue by bukzor** [pre-commit/pre-commit#500] opened 2017-02-25 00:27 UTC
A broken symlink isn't a file.

**Comment by chriskuehl** [comment] 2017-02-25 00:33
Dupe of #191 and #341. We're working on this in https://github.com/chriskuehl/identify and https://github.com/pre-commit/pre-commit/pull/329 (that PR will be revived eventually).

**Closed by chriskuehl** 2017-02-25 00:33 UTC
