### ISSUE TITLE
Machine-readable output?

### ISSUE THREAD

**Issue by hterik** [pre-commit/pre-commit#2223] opened 2022-01-25 09:55 UTC
Hi
We run pre-commit as part of CI check jobs and there want to collect data about the checks being run for statistics on most common failures, hook runtimes and for inline presentation of error messages for users in the diff-view.

What would be the best way to collect this data? The current output of pre-commit is not that obvious to parse and not guaranteed to be stable, how open are you to something like a --json flag producing stable and easily parseable output?
We are using python ourselves so could import the internal pre_commit functions, but most of them are private and write straight to output stream anyway, so such approach would also require some changes.

**Comment by asottile** [comment] 2022-01-25 13:54
there is no public api beyond `clientlib` so accessing anything at the python level is not supported

the rest of this is a duplicate of #1332

**Closed by asottile** 2022-01-25 13:54 UTC
