### ISSUE TITLE
[corner case?] pre-commit fails to add origin when there's settings under origin in the user-global config

### ISSUE THREAD

**Issue by webknjaz** [pre-commit/pre-commit#1403] opened 2020-04-20 12:43 UTC
Basically, if you do
```console
git config --global --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'
```
it effectively adds 
```ini
[remote "origin"]
	fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
```
to `~/.gitconfig`.

And then the failure looks like this:
```console
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.git.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'remote', 'add', 'origin', 'https://github.com/pre-commit/pre-commit-hooks.git')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: remote origin already exists.
    
Check the log at ~/.cache/pre-commit/pre-commit.log
```

The solution would be to check if the remote exists and maybe instead do
```console
git config --local remote.origin.url 'https://github.com/pre-commit/pre-commit-hooks.git'
git config --local remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
git fetch --all
```

**Comment by asottile** [comment] 2020-04-20 16:49
why would you do `git config --global --add remote.origin.fetch '+refs/pull/*/head:refs/remotes/origin/pr/*'` ?

this seems self inflicted

**Comment by webknjaz** [comment] 2020-04-20 16:51
It basically makes Git auto-fetch all pull requests from all repos from the GitHub's read-only namespace. I used to do it per repo and now I'm experimenting with a setting being in one place instead.

**Comment by asottile** [comment] 2020-04-20 16:56
you're configuring a remote on every repository that might not exist -- it breaks `git remote` as well (I took your command and used `wat` instead):

```console
$ git remote -v
origin	git@gitlab.com:pycqa/flake8 (fetch)
origin	git@gitlab.com:pycqa/flake8 (push)
wat	
```

**Comment by webknjaz** [comment] 2020-04-20 16:57
yeah I know about this side effect

**Comment by asottile** [comment] 2020-04-20 16:57
your setting also breaks `git fetch --all`

**Comment by webknjaz** [comment] 2020-04-20 16:58
well, "breaks". it still works but outputs errors for remotes without url

**Comment by asottile** [comment] 2020-04-20 16:59
it exits nonzero, so any scripted use would be broken

**Comment by webknjaz** [comment] 2020-04-20 17:01
Ah, right. anyway, pre-commit should either change it to not hit this error or catch it and print out a bit more meaningful error message.

**Comment by asottile** [comment] 2020-04-20 17:05
seems silly to "support" your broken config, but I believe #1404 will work? can you try it out

**Comment by webknjaz** [comment] 2020-04-20 17:06
You broke GitHub! (seeing a unicorn page right now 😆)

**Comment by asottile** [comment] 2020-04-20 17:07
the branch name is `poorly_configured_git` if you want to pull it down

**Comment by webknjaz** [comment] 2020-04-20 17:08
Nah, it's okay already, added a few notes there.

**Comment by webknjaz** [comment] 2020-04-20 17:10
Alternatively, you could feed it your own config path to completely ignore the system and user-global configs.

**Comment by asottile** [comment] 2020-04-20 17:12
that breaks people with proxy / etc. setups

**Comment by asottile** [comment] 2020-04-20 18:16
actually, I think this is a bug/regression in git -- I can't reproduce the errors you're seeing in git 2.17.1 so I'm going to report this to their mailing list instead

**Comment by asottile** [comment] 2020-04-20 18:18
or in 2.25.1 🤔 -- what version of git are you using?

**Comment by webknjaz** [comment] 2020-04-20 18:19
I have a very old Git on this machine (my regular laptop is in repairs 😢). So I'll try to update it as soon as I defeat homebrew.
```console
$ git --version
git version 2.7.4 (Apple Git-66)
```

**Comment by asottile** [comment] 2020-04-20 18:20
oh then it's probably fixed already -- I'm going to close this then -- the complexity to support this weird use case I don't think is worth it.  if it comes up again I'll reconsider

**Closed by asottile** 2020-04-20 18:20 UTC
