### ISSUE TITLE
Support for interaction while running pre-commit hook

### ISSUE THREAD

**Issue by potiuk** [pre-commit/pre-commit#1127] opened 2019-08-31 12:13 UTC
Sometimes we have a need for a user to answer some interactive question while running pre-commit hook. Typical example is - if you run your hooks via docker image and it needs to be rebuilt, it would be great to be able to ask user if the image should be rebuid/skipped or pre-commit should abort. This is the case we have now. For now I think pre-commit framework takes over stdout so that we cannot really make such interactive question. It would be great to be able to ask such questions.

Happy to make a PR maybe some guidance on how to do it would be helpful

**Comment by asottile** [comment] 2019-08-31 13:49
Duplicate of #871 and #872 

pre-commit already automatically rebuilds docker images if they are missing, is that not working for you?

**Closed by asottile** 2019-08-31 13:49 UTC

**Comment by potiuk** [comment] 2019-09-02 00:26
It was my own docker image build (we have quite complex scripts to build the right docker image as we have multi-stage build for multiple purposes) and we are also using --cache-from to use docker images built on DockerHub (so that you do not have to rebuild it all locally). So I do some optimisation with detecting whether I even have to attempt to run docker build (there are cases with multi-staging and with --cache-from) where it takes minutes to just run through "docker build ." without need to rebuild anything. And I wanted to inform the user that the docker image might need to be rebuild but live the freedom to decide whether to do it or not (for example if you work offline or have slow connection you might choose to not rebuild the latest image). 

However I do not think it is needed in pre-commit itself. Thanks for the #871 and #872 pointest - I just added /dev/tty interaction with my own script and it works well, so this issue can indeed be closed. However maybe worth to update documentation to mention that such interaction is possible via /dev/tty ?

**Comment by potiuk** [comment] 2019-09-02 00:29
In case you are interested @asottile - i've added such interactivity in this PR: https://github.com/apache/airflow/pull/5976 - including also capability of stopping running containers via ^C - often you need to have dumb-init as entry point rather than bash scripts if you want to be able to ^C such pre-commits. It might be also worth mentioning in the documentation. Happy to make PR if you think either of those two make sense.

**Comment by asottile** [comment] 2019-09-02 00:39
Yeah it's probably worth documenting / advocating for an init system -- probably can add something to [pre-commit.com#docker](https://pre-commit.com/#docker)

As for `/dev/tty` I'd rather leave that undocumented -- it's ~usually a bad user experience and isn't super portable or reliable

**Comment by potiuk** [comment] 2019-09-02 10:46
Yeah. The /dev/tty is a hack indeed. As for docker/dumb-init - I will prepare blog post about experiences of adding pre-commits to Apache Airflow and have a talk about it and will update the documentation then. Should be in the next month or so :)

**Comment by asottile** [comment] 2019-09-02 14:06
sounds great! thanks again :)
