### ISSUE TITLE
FileNotFoundError when using ```pre-commit install --install-hooks```

### ISSUE THREAD

**Issue by dgarhdez** [pre-commit/pre-commit#1230] opened 2019-11-28 15:20 UTC
Hi!

I'm using pre-commit in the project I'm working on and right after installing the requirements in the conda environment I've created, I get the following error:

```
 C:\Users\DANIGARC\Desktop\repos\POC-BigDataProject-Wind>pre-commit install --install-hooks
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: 'H:\\My Documents/.cache\\pre-commit\\.lock'
Traceback (most recent call last):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\error_handler.py", line 46, in error_handler
    yield
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\main.py", line 265, in main
    store = Store()
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 53, in __init__
    with self.exclusive_lock():
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 81, in exclusive_lock
    with file_lock.lock(os.path.join(self.directory, '.lock'), blocked_cb):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\file_lock.py", line 62, in lock
    with open(path, 'a+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\My Documents/.cache\\pre-commit\\.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DANIGARC\AppData\Local\Continuum\anaconda3\envs\tertiary\Scripts\pre-commit.exe\__main__.py", line 7, in <module>
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\main.py", line 305, in main
    'Command {} failed to exit with a returncode'.format(args.command),
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\error_handler.py", line 54, in error_handler
    _log_and_exit(msg, e, traceback.format_exc())
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\error_handler.py", line 34, in _log_and_exit
    store = Store()
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 53, in __init__
    with self.exclusive_lock():
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 81, in exclusive_lock
    with file_lock.lock(os.path.join(self.directory, '.lock'), blocked_cb):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\file_lock.py", line 62, in lock
    with open(path, 'a+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\My Documents/.cache\\pre-commit\\.lock'
```

**Comment by asottile** [comment] 2019-11-28 16:04
Could you provide more information?  What version are you using? How did you install it? And can you attach the log file that it produces on crash?

**Comment by dgarhdez** [comment] 2019-11-28 16:25
Version 1.17.0
Installed through a ```requirements.txt``` file using ```pip install -r requirements.txt```
Where could I find the log it creates on crash? I've never had to deal with such issues...

**Comment by asottile** [comment] 2019-11-28 16:29
oh maybe it's too early to write the log, hmmm

can you try the latest version?  there was a bug like this at some point that was fixed -- wondering if it's the same one

**Comment by dgarhdez** [comment] 2019-11-28 16:32
I just tried upgrading, and getting the same error.

Successfully installed pre-commit-1.20.0

(tertiary) C:\Users\DANIGARC\Desktop\repos\POC-BigDataProject-Wind>pre-commit install --install-hooks
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: 'H:\\My Documents/.cache\\pre-commit\\.lock'
Traceback (most recent call last):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\error_handler.py", line 72, in error_handler
    yield
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\main.py", line 298, in main
    store = Store()
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 54, in __init__
    with self.exclusive_lock():
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 82, in exclusive_lock
    with file_lock.lock(os.path.join(self.directory, '.lock'), blocked_cb):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\file_lock.py", line 62, in lock
    with open(path, 'a+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\My Documents/.cache\\pre-commit\\.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DANIGARC\AppData\Local\Continuum\anaconda3\envs\tertiary\Scripts\pre-commit.exe\__main__.py", line 7, in <module>
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\main.py", line 343, in main
    'Command {} failed to exit with a returncode'.format(args.command),
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\error_handler.py", line 80, in error_handler
    _log_and_exit(msg, e, traceback.format_exc())
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\error_handler.py", line 36, in _log_and_exit
    store = Store()
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 54, in __init__
    with self.exclusive_lock():
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\store.py", line 82, in exclusive_lock
    with file_lock.lock(os.path.join(self.directory, '.lock'), blocked_cb):
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\danigarc\appdata\local\continuum\anaconda3\envs\tertiary\lib\site-packages\pre_commit\file_lock.py", line 62, in lock
    with open(path, 'a+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\My Documents/.cache\\pre-commit\\.lock'

**Comment by dgarhdez** [comment] 2019-11-28 16:34
Now I'm curious because my python instalation, conda environment, git, everything is in C:.

Why is it going through H:?? Any clue??

**Comment by asottile** [comment] 2019-11-28 16:37
One thing that's pretty weird is I expect it to try and write to `c:\users\danigarc\.cache\pre-commit` but for some reason it's writing to `H:`???

Can you try the following for me in a python shell:

```pycon
>>> import os
>>> os.path.expanduser('~/.cache')
'C:\\Users\\asott/.cache'
>>> os.environ['HOME']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'
>>> os.environ['HOMEPATH']
'\\Users\\asott'
>>> os.environ['USERPROFILE']
'C:\\Users\\asott'
```

**Comment by dgarhdez** [comment] 2019-11-28 16:44
![image](https://user-images.githubusercontent.com/18012696/69822476-c0161d80-1206-11ea-8e75-171ec4277089.png)

**Comment by asottile** [comment] 2019-11-28 16:46
what about `HOME`?

**Comment by asottile** [comment] 2019-11-28 16:49
(I suspect something odd on your system is setting `HOME` which doesn't mean anything on windows)

I've fixed this in python 3.8 if you're able to upgrade to it: https://docs.python.org/3/whatsnew/3.8.html#os-path

**Comment by dgarhdez** [comment] 2019-11-28 16:50
```os.environ["HOME"]``` yields ```'H:\\My Documents'```

**Comment by asottile** [comment] 2019-11-28 16:52
yep that's the problem!   If you can find out how to unset that variable (or figure out what's setting it in the first place) that should fix the problem

Alternatively, if you can use python3.8 instead of whichever version you're currently using that would fix it too

**Comment by asottile** [comment] 2019-11-28 16:55
interestingly enough, #960 is a duplicate of the same problem -- it has a workaround as well

**Comment by dgarhdez** [comment] 2019-11-28 17:05
Thanks! That definitely unlocked that error, but now I'm getting the following regarding flake8 (log attached)
[pre-commit.log](https://github.com/pre-commit/pre-commit/files/3902629/pre-commit.log)


(tertiary) C:\Users\DANIGARC\Desktop\repos\POC-BigDataProject-Wind>pre-commit install --install-hooks
pre-commit installed at .git\hooks\pre-commit
[INFO] Initializing environment for https://gitlab.com/pycqa/flake8.
An unexpected error has occurred: CalledProcessError: Command: ('C:\\Program Files\\Git\\cmd\\git.exe', 'fetch', 'origin', '--tags')
Return code: 128
Expected return code: 0
Output: (none)
Errors:
    fatal: unable to access 'https://gitlab.com/pycqa/flake8/': SSL certificate problem: self signed certificate in certificate chain

**Comment by asottile** [comment] 2019-11-28 17:08
does this reproduce the same problem?

```bash
git clone https://gitlab.com/pycqa/flake8
```

**Comment by dgarhdez** [comment] 2019-11-28 17:09
Yup. I guess the issue is in my machine! I'll research on this.

**Comment by asottile** [comment] 2019-11-28 17:10
sounds good!  let me know if you find anything specific (comment here if you do) -- for now I'm going to close this as we got to the bottom of the original issue -- thanks for the issue 🎉

**Closed by asottile** 2019-11-28 17:10 UTC
Labels: question, windows
