### ISSUE TITLE
Raise error when using branch name as `rev`

### ISSUE THREAD

**Issue by verhovsky** [pre-commit/pre-commit#1255] opened 2019-12-28 01:34 UTC
and print the SHA hash of the latest commit on that branch instead, for easier copy/pasting.

https://pre-commit.com/#using-the-latest-version-for-a-repository

> pre-commit assumes that the value of rev is an immutable ref (such as a tag or SHA) and will cache based on that. Using a branch name (or HEAD) for the value of rev is not supported and will only represent the state of that mutable ref at the time of hook installation (and will NOT update automatically).

You should explicitly check for that and warn people (or error) instead of expecting them to read the docs. This repo makes that mistake for example https://github.com/doublify/pre-commit-clang-format

**Comment by asottile** [comment] 2019-12-28 01:43
this is a dupe of #974 👍

**Closed by asottile** 2019-12-28 01:43 UTC
