### ISSUE TITLE
FR: Support for template config files

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit/pre-commit#1308] opened 2020-02-01 23:03 UTC
## Motivation

Every repo that uses pre-commit hooks has its own config file and there is no way to administer these config files in a central place (to my knowledge). This means the different repos may use different versions of the same hook. If I want to add a hook to all repos, I have to do so manually in every repo. A common use case is all repos in a GitHub organization.

## Proposed solution in detail

At initialisation, pre-commit could allow specifying a config file. The CLI could be extended to support remote and local config file storage:

-  `pre-commit install --config https://raw.githubusercontent.com/path/to/raw/.pre-commit-config.yaml`
- `pre-commit install --config file:///abs/path/to/config-1.yaml`.

The file name should be specified to allow different template config files to be stored in the same place. `.pre-commit-config.yaml` gains a key `template:` that refers to the template config file path as exemplified above. To detach a repo's `.pre-commit-config.yaml` from the template, simply remove the key in the config file.

`pre-commit autoupdate` should by default also check if there is a template config linked in the `.pre-commit-config.yaml`. If yes, it should sync both hooks *and* version of the repo, unless `--no-template-sync` or similar is given, which would then behave as the current implementation of `autoupdate`. 

## Notes

- This is not a breaking API change in my understanding.
- We must make sure not to confuse the use of *template* because it is already used in the documentation in [another context](here: https://pre-commit.com/#pre-commit-init-templatedir).

***

Do you think this is a reasonable extension? I searched but I could not find a similar proposal in the issues of this repo.

**Comment by lorenzwalthert** [comment] 2020-02-01 23:09
Ups I think this crossed with #1307.

**Comment by lorenzwalthert** [comment] 2020-02-01 23:26
I tried your suggestion in #1307, but I think this is not exactly what me and @pat-s mean. Because it's not that we want the config to have a different name, but rather to have a config file *copied* from somewhere into the repo and put it under version control there. Because with 

```
pre-commit install --config /path/to/template
```

the config file is not copied into the repo but linked somehow if I understand that correctly (at least when the file is not in a sub directory of the git root, this seems non-transparent to me). Our idea is to provide a convenient mechanism to create and update the config file from a template that materialises in the git root.

**Comment by asottile** [comment] 2020-02-01 23:35
I think it does what you expect, I just used a configuration that was in the current working directory -- it could be anywhere (for example like `/etc/mycompany/pre-commit-config.yaml`)

**Comment by asottile** [comment] 2020-02-01 23:39
the way it works is it bakes in the configuration path into the `.git/hooks/pre-commit` script such that when git operations are run they will use that configuration

```console
$ pre-commit install --config /etc/mycompany/pre-commit-config.yaml
pre-commit installed at .git/hooks/pre-commit
$ grep 'ARGS =' .git/hooks/pre-commit
ARGS = ['hook-impl', '--config=../../../../etc/mycompany/pre-commit-config.yaml', '--hook-type=pre-commit']
```

**Comment by asottile** [comment] 2020-02-03 18:52
fwiw, the original request in this issue is some sort of extends / inheritance / includes which is a duplicate of a few issues: #1069 #1158 #466 #1203

there's generally ~4 existing solutions which work for this today:
- the sketch outlined in https://github.com/pre-commit/pre-commit/issues/731#issuecomment-376945745
- using symlinks to a well known system location
- using symlinks to a submodule
- using `--config` to a well known location when running `pre-commit run` / `pre-commit install`

as outlined in the linked issues, I'm not going to add such a feature to pre-commit directly for a couple of reasons:
- pre-commit is designed as a reaction to centrally managed hooks
- it makes cachability difficult/intractable
- there's already solutions without adding the functionality directly

**Closed by asottile** 2020-02-03 18:52 UTC

**Comment by asottile** [comment] 2020-02-03 18:53
note also for updating / etc. you may find [`pre-commit autoupdate`](https://pre-commit.com/#pre-commit-autoupdate) and/or  [all-repos](https://github.com/asottile/all-repos) useful

**Comment by lorenzwalthert** [comment] 2020-02-03 21:26
Thanks for the in-depth discussion, I appreciate that 👍 .
