### ISSUE TITLE
node hooks fails SSL CERTIFICATE verification failure.

### ISSUE THREAD

**Issue by jackton1** [pre-commit/pre-commit#1125] opened 2019-08-29 23:47 UTC
Getting errors running a node pre-commit hook

```bash
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/Users/tonyejack/.virtualenvs/content_library/bin/python3.6', '-mnodeenv', '--prebuilt', '--clean-src', '/Users/tonyejack/.cache/pre-commit/reposl__4ux5/node_env-default')
Return code: 1
Expected return code: 0
Output: 
    {'User-Agent': 'nodeenv/1.3.3 (https://github.com/ekalinin/nodeenv/)'}
    
Errors: 
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
        server_hostname=server_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
        _context=self, _session=session)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
        self._sslobj.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/tonyejack/.virtualenvs/content_library/lib/python3.6/site-packages/nodeenv.py", line 1481, in <module>
        main()
      File "/Users/tonyejack/.virtualenvs/content_library/lib/python3.6/site-packages/nodeenv.py", line 1068, in main
        opt.node = get_last_stable_node_version()
      File "/Users/tonyejack/.virtualenvs/content_library/lib/python3.6/site-packages/nodeenv.py", line 998, in get_last_stable_node_version
        response = urlopen('https://%s/dist/latest/' % src_domain)
      File "/Users/tonyejack/.virtualenvs/content_library/lib/python3.6/site-packages/nodeenv.py", line 565, in urlopen
        return urllib2.urlopen(req)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

```

**Comment by asottile** [comment] 2019-08-29 23:53
duplicate of #1017

**Closed by asottile** 2019-08-29 23:53 UTC
