### ISSUE TITLE
Ability to run with unstaged configuration

### ISSUE THREAD

**Issue by acdha** [pre-commit/pre-commit#848] opened 2018-10-15 19:55 UTC
Currently pre-commit prevents you from running with unstaged configuration. This makes it extremely tedious to test pre-commit configuration since you have to manually amend the config commit before making the commit you wanted to test to avoid getting the “[ERROR] Your pre-commit configuration is unstaged. `git add .pre-commit-config.yaml` to fix this.” warning.

I ran into this while trying to debug why `exclude:` was failing to apply to a hook.

**Comment by asottile** [comment] 2018-10-15 19:57
if you use `--files` or `--all-files` this limitation is lifted.

The reason this was added is the first thing `pre-commit` does is remove any unstaged changes so that it is [only linting the things you have checked in](https://pre-commit.com/#pre-commit-during-commits)

**Comment by asottile** [comment] 2018-10-15 20:01
and by removing unstaged changes, it would remove your modifications to `.pre-commit-config.yaml` leading to _very confusing_ results ;)

**Comment by acdha** [comment] 2018-10-15 20:12
The problem I was trying to work around was a bug in the Prettier hook (they added the config to register for HTML before shipping a release with HTML support) which meant I was testing the file include/exclude logic.

**Comment by asottile** [comment] 2018-10-15 20:15
yep! totally understand that, here's what would have happened if that error message didn't fire:

1. it would have stashed the `.pre-commit-config.yaml`'s contents and blown away your modifications
2. then only ran linters against the staged files

when what you probably wanted was to run `pre-commit run --all-files` to test that your modifications to the configuration applied the inclusion / exclusion correctly.

the zero-args `pre-commit` (or `pre-commit run`) ~roughly mimics what would be run as a side-effect of `git commit`.

**Closed** 2018-10-22 19:05 UTC
Labels: question

**Comment by VikashKothary** [comment] 2021-03-04 20:24
Hi @acdha,

I've been using `pre-commit run --all-files` and it says there are `(no files to check)` unless I stage the files. 

The above conversation makes me think that this is not expected behaviour? 

Any insight you could provide would be much appreciated.

**Comment by asottile** [comment] 2021-03-04 21:47
if the files are not part of `git` at all then yes that's an expected behaviour

**Comment by VikashKothary** [comment] 2021-03-07 21:03
@asottile Thank you for your response. That makes sense. 

I guess running it on files outside `git` is out of scope? My understanding was `--all-files` meant all files but it seems to mean `--include-staged`? Is there any way to `--include-unstaged` as well?

The use case here is that I often run `pre-commit run --all-files` during development. The `--all-files` is deceptive because you think your code is passing linting but when you commit then it fails.

**Comment by asottile** [comment] 2021-03-07 21:13
yes, **the framework is based around files in git -- if your files aren't in `git` then they won't be linted.**

you can always use `git add` or `git add --intent-to-add`

your suggestion is definitely not what you want, because that'd lint junk in your virtualenv and other things as well -- and the complexity for implementing a full inclusion / exclusion system would not be welcome

**Comment by asottile** [comment] 2021-03-07 21:14
locking since the recent messages are off-topic from the original message (which was purely around whether the `.pre-commit-config.yaml` was staged)
