### ISSUE TITLE
On Windows 10, installing Black gives a "symbolic link privilege not held" error

### ISSUE THREAD

**Issue by jimbo1qaz** [pre-commit/pre-commit#1297] opened 2020-01-26 08:29 UTC
I encountered an issue similar to #891. I'm not sure if it's the same issue.

My .pre-commit-config.yaml file contains:

```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
```

When I run `pre-commit install` followed by `git commit`, I get the following error:

`ERROR: Could not install packages due to an EnvironmentError: [('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\authors.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\authors.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\blackd.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\blackd.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\change_log.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\change_log.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\contributing.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\contributing.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\contributing_to_black.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\contributing_to_black.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\editor_integration.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\editor_integration.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\ignoring_unmodified_files.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\ignoring_unmodified_files.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\installation_and_usage.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\installation_and_usage.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\license.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\license.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\pyproject_toml.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\pyproject_toml.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\show_your_style.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\show_your_style.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\testimonials.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\testimonials.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\the_black_code_style.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\the_black_code_style.md', 'symbolic link privilege not held'), ('C:\\Users\\nyanpasu\\.cache\\pre-commit\\repohrc4rm0w\\docs\\version_control_integration.md', 'C:\\Users\\nyanpasu\\AppData\\Local\\Temp\\pip-req-build-jx1nukhl\\docs\\version_control_integration.md', 'symbolic link privilege not held')]`

#891 claims:

> ok I played with this on my dad's computer. this was the only way I could reproduce the problem

I was unable to *not* reproduce the problem. The only workaround I found was running `git commit` as admin. I have Windows Developer Mode enabled, and `mklink` works without admin.

**Comment by asottile** [comment] 2020-01-26 17:31
duplicate of #891, either enable the privilege for your user or reinstall git with symlinks disabled

**Closed by asottile** 2020-01-26 17:31 UTC

**Comment by nyanpasu64** [comment] 2020-11-18 01:10
> to recover, I ran pre-commit clean as an admin, and then pre-commit run black --all-files worked fine

seems to work
