### ISSUE TITLE
Add Metahook to Manage Additional Dependencies

### ISSUE THREAD

**Issue by Skylion007** [pre-commit/pre-commit#1903] opened 2021-05-09 18:45 UTC
So one nagging issue I've noticed in deploying pre-commit is managing / upgrading additional dependencies for complex hooks (specifically flake8 extensions). To follow up on the thread of : https://github.com/pre-commit/pre-commit/issues/730#issuecomment-835856309

TLDR: This hook would parse the requirements files and update the pre-commit config by manually inserting each requirement in the YAML array. It could potentially sync in the other direction as well. Each requirement would be listed in the pre-commit-config so caching would function properly.

I am confused why a sync-requirements metahook would not be a good solution here per the discussion in the thread? You could use similar logic for hooks that are checked  for useless excludes and such, but instead focus on parsing the requirements of a specific file (requirements.txt / package.json and then pasting those pinned requirements into the yaml). Several people have written local hooks or scripts to those using internal pre-commit APIs or external YAML parsers, but those are often specific only to one format or language. 
* A clean way to do this within the pre-commit framework as a metahook would be greatly appreciated and would reduce the maintenance burden. All the issues concerning security would be no different from normal metahook tests (making sure the tests still apply). It would remove the need for maintaining two sets of requirements for pre-commit and external testing frameworks and allow project requirements to be easily imported into hooks that would benefit from them like mypy or other hooks that could use project dependencies. 
* Standardizing this within the pre-commit yaml spec would be ideal using a custom token / keyword / comment two way synchronize it. Otherwise, it would be at risk of breaking.
* There is no thirdparty API for metahooks at this time, correct? They have to be added to this repo anyway or act as a metahook in a non-standard way. There is a first party API for parsing the pre-commit config, but no API for writing to it.
* Hooks that modify a pre-commit-config for formatting or other reasons should be included in a metahook.
* By explicitly listing all the requirements in the yaml, caching will not be an issue.
* It shouldn't have any more security concerns that checking for useless hooks or other hook checks that would maintain or update the config.
* Alternatively, clarify that metahooks aren't special hooks and have the same API access as normal hooks? Its a bit odd they are embedded in the repo.
* Plan-B would be to implement this a specific hook in a similar way to pretty-format-yaml, but then it would live on as a third party hook and may lag behind supported languages and features of pre-commit.

**Comment by Skylion007** [comment] 2021-05-09 18:52
Similar to https://github.com/pre-commit/pre-commit/issues/945, but I am advocating making this a first party hook since it would either require independent parsing / writing of the config file and needs some standardized API / way of indicating where the API is synched to and from.

**Comment by asottile** [comment] 2021-05-09 19:44
this is a dupe of #945 -- please continue the discussion there

**Closed by asottile** 2021-05-09 19:44 UTC
