### ISSUE TITLE
A way to suspend errors

### ISSUE THREAD

**Issue by Nihisil** [pre-commit/pre-commit#1342] opened 2020-02-22 08:35 UTC
Is there a way to suspend error for specific hooks?

Configuration:
```
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
```

I want to see errors from `flake8` always. And from `black`, I don't want to have a blocking commit error. 

So, `black` will format files and show what files were formatted before commit, but these issues will not block the commit itself. Is there a configuration for behavior like that?

**Comment by asottile** [comment] 2020-02-22 15:09
Duplicate of #1086 #879 #806 #999 #747

there is no option because modifying the staging area is:
1. not a safe operation
2. not a correct operation
3. would make several of the current supported features impossible

the specifics are outlined in the duplicates -- there are ways to break this and stage the files anyway but you do so at your own risk

**Closed by asottile** 2020-02-22 15:09 UTC

**Comment by asottile** [comment] 2020-02-22 15:10
you may also find [this useful](https://stackoverflow.com/a/59745587/812183) (upvote if you found useful) -- but again this is strongly discouraged
